# 02_HISTORY_NARRATIVE — TRUE GROUPED MASTER v98

**Назначение:** Исторический каркас и сюжетная логика серии.

**Правило v98:** это рабочий групповой файл. Новые находки добавлять сюда, а не создавать numbered MD. Каждый блок ниже сохраняет исходный путь, чтобы ничего не потерять.

## Быстрый состав группы

- `baptists_v93/03-act-zero-master-prehistory.md` (14507 bytes)
- `baptists_v93/04-origins-imperial-admin-orthodox-relations-master.md` (31989 bytes)
- `baptists_v93/08-chronology-data-model-master.md` (12570 bytes)

---



---

## [1] SOURCE: `baptists_v93/03-act-zero-master-prehistory.md`

# 03. Act zero master prehistory

## Назначение нулевого акта

Нулевой акт нужен не для того, чтобы “удлинить родословную баптистов до Руси”, а чтобы объяснить поле, в котором позднее появятся евангельско-баптистские вопросы:

- кто имеет право читать и толковать Писание;
- как соотносятся церковь, народ и государство;
- где проходит граница совести;
- почему добровольная община воспринималась как социальная угроза;
- почему перевод Библии и домашнее чтение становятся взрывной темой.

## Безопасная рамка

Правильно:

> До XIX века в русской истории существовали разные формы религиозного инакомыслия, книжности, споров о церковной жизни и контактов с западным христианством. Они не были баптистами, но помогают понять, почему в XIX веке чтение Библии, личная вера и добровольная община стали такими острыми вопросами.

Неправильно:

> Баптисты были в России с древних времён под другими именами.

## Основные сюжеты

### Крещение Руси

Использовать как начало церковно-государственного и культурного поля, не как начало баптистской истории. Важно не писать “вся Русь мгновенно стала христианской”. Христианизация — процесс, разный по регионам, элитам, городам и народной среде.

### Писание и книжность

Ключевой вопрос: была ли Библия доступна как личная книга? В древней/средневековой Руси библейская традиция была реальной, но не равна поздней евангельской культуре домашнего чтения, кружков, проповеди и миссии.

### Стригольники и “жидовствующие”

Использовать только как примеры церковных кризисов и инакомыслия. Не называть “русской Реформацией” без оговорок и не связывать генеалогически с баптистами.

### Нестяжатели / иосифляне

Полезны как спор о монашестве, церковной собственности, власти и духовной жизни, но не как прямой предок баптизма.

### Реформация рядом с Московией

На русско-рутенских землях ВКЛ/Речи Посполитой протестантские процессы были реальностью. Но это не значит “Реформация Московской Руси”. Нужно держать политико-географические границы.

### Иностранные протестанты в Московии

Немецкие, английские, голландские и другие протестанты в Москве/Немецкой слободе — важный контактный фон. Но в основном это иностранные общины, а не русское баптистское движение.

### Старообрядцы

Показывают драму обряда, власти, церковной нормы и совести. Но старообрядчество — не баптизм и не “евангельское движение”.

### Российское библейское общество

Важный мост к XIX веку: перевод, распространение текста, русский язык, контроль и страх перед неконтролируемым чтением.

### Молокане и водные молокане

Самый близкий пролог к баптистскому XIX веку, но формула должна быть точной: молоканская среда была важной почвой и переходной зоной, особенно там, где возникал вопрос водного крещения, но молокане не равны баптистам.

## Что должно войти в статью `do-kury`

1. Сцена: не “до баптистов была пустота”, а долгая история вопроса о совести и Писании.
2. Блок “Что нельзя называть баптизмом”.
3. Короткая карта: Русь / ВКЛ / Московия / немецкие колонии / юг империи.
4. Архивная пауза: Библия/перевод/книжность.
5. Переход к XIX веку: молокане, штунда, немецко-меннонитская среда, Курская дата 1867.

## Уровни уверенности

| Сюжет | Статус |
|---|---|
| Крещение Руси как начало православно-государственного поля | B1 |
| Доступность Писания как сложная, не протестантская по форме традиция | B1 |
| Русско-рутенская Реформация рядом с Московией | B1 |
| Прямое происхождение баптизма от древнерусских движений | X |
| Молоканская среда как часть предыстории | B1/B2 |
| Водные молокане как ближайший переходный узел | B1, требует case-check |

---

# V39 no-loss expansion — режим «ничего не урезать»

Этот раздел добавлен после замечания: **при консолидации нельзя терять факты, выводы, абзацы, оговорки и рабочие решения из предыдущих проходов**. Поэтому v39 — не краткая выжимка и не рекламный summary, а рабочий master-пакет: в нём должны сохраняться все проверенные линии исследования, но без расползания на сотни файлов.

Правило v39:

1. **Старые v1–v26 и round-файлы не импортируются в репозиторий как рабочая структура**, но считаются черновым архивом исследования, из которого нельзя выбрасывать подтверждённые выводы.
2. **Каждый факт переносится в один из 10 master-файлов**, а не в новый одноразовый файл.
3. **Ни один вывод не должен исчезать при укрупнении**: если вывод ещё не готов для статьи, он переносится в статус `LEAD`, `QUESTION`, `BIOCASE-D`, `MEDIA-GATE`, `ARCHIVE-REQUEST` или `DO-NOT-ASSERT-YET`.
4. **Не сжимать до тезисов там, где нужна аргументация**: важные спорные темы требуют абзацев, контраргументов, источниковой критики и плана проверки.
5. **Не превращать источники в “истину”**: баптистский, православный, советский, зарубежный, светский, архивный и семейно-мемуарный голоса должны быть разведены.


## V39: что нельзя потерять в нулевом акте

Нулевой акт нужен не для того, чтобы “удлинить родословную баптистов”, а чтобы объяснить религиозную почву, на которой баптистская идентичность XIX века стала возможной и конфликтной.

### Нельзя писать

- “Баптисты существовали на Руси с древности”.
- “Стригольники были баптистами”.
- “Жидовствующие были протобаптистами”.
- “Старообрядцы были евангельскими христианами”.
- “Молокане автоматически равны баптистам”.

### Нужно писать

- До баптизма были разные формы религиозного несогласия, книжности, народного библеизма, духовного христианства и антиинституционального поиска.
- Эти движения не являются прямыми баптистскими предками, но они объясняют, почему чтение Писания, домашние собрания, критика обрядовой формальности и добровольная община могли восприниматься как опасная альтернатива.
- Молоканская и духовно-христианская среда важна для отдельных биографий, особенно для Проханова, но не должна стирать различие между молоканством, евангельским христианством и баптизмом.

### BioCase для нулевого акта

В нулевом акте можно использовать не “героев-баптистов”, а **типы религиозной памяти**:

1. книжник/читатель Писания;
2. семейная религиозная традиция вне приходского контроля;
3. духовно-христианский дом;
4. переход от наследуемой религиозности к личному обращению;
5. конфликт между обрядовой принадлежностью и исповедуемой верой.

Эти типы нельзя выдавать за прямую баптистскую историю. Они нужны как фон, а не как генеалогическая лестница.


---

## V39. No-loss уточнение для Нулевого акта

Нулевой акт должен сохранить всю сложность предыстории, но не превратиться в ложную генеалогию. Важно не потерять две вещи одновременно:

1. **Русь и Россия до XIX века не были “баптистскими”** — нельзя выводить баптистов напрямую от крещения Руси, стригольников, жидовствующих, нестяжателей или старообрядцев.
2. **Но религиозная предыстория важна** — книжность, споры о Писании, старообрядческий разрыв, духовные христиане, молокане, водные молокане, Российское библейское общество, западные протестанты в Московии и Российской империи создавали поле, в котором позднее баптистская проповедь могла быть услышана.

### Что обязательно сохранить

- Крещение Руси — не “первый баптизм”, а фон христианизации и церковно-государственной связки.
- Стригольники и жидовствующие — не протобаптисты, а примеры религиозных споров и антииерархических/библейских напряжений.
- Нестяжатели — не евангельские христиане, а пример внутренней церковной аскетико-социальной критики.
- Старообрядцы — не баптисты, но пример того, как вопрос совести, обряда и государства мог раскалывать общество.
- Молокане и духовные христиане — ближе к предыстории русского баптизма, потому что многие ранние баптисты вышли из этой среды, но и они не “почти баптисты”.
- Водные молокане — особенно важный мост, но мост не тождественен конечной форме.
- Российское библейское общество — важно для распространения Писания, но не было баптистским проектом.

### Безопасная формула для пролога

> До 1867 года история ещё не является историей русских баптистов в собственном смысле. Это история религиозного поля, в котором постепенно накапливались вопросы Писания, совести, личной веры, общины, перевода, чтения и отношений с государством. Русский баптизм возник не из пустоты, но и не из прямой непрерывной “тайной баптистской линии”.


---

## [2] SOURCE: `baptists_v93/04-origins-imperial-admin-orthodox-relations-master.md`

# 04. Origins, imperial administration, Orthodox relations — master

## Центральная идея

Русский баптизм возник не из одной причины. Это пересечение местных библейских поисков, молоканской среды, немецко-меннонитских контактов, немецко-баптистской сети, петербургского евангельского круга, имперской правовой системы и православной миссионерской реакции.

## Три линии истоков

### Южная линия

Штунда, немецкие колонии, меннониты, меннонитские братья, молоканские переходы, крещение по вере, сельские общины. Здесь особенно опасно смешивать:

- штундистов;
- молокан;
- меннонитов;
- меннонитских братьев;
- баптистов;
- евангельских христиан.

### Кавказ / Кура / 1867

20 августа 1867 — крещение Н. И. Воронина в Куре — удобная формальная дата русского баптизма. Но она не объясняет всё движение. В серии её нужно ставить как “точку кристаллизации”, а не как миф о внезапном рождении.

### Петербургская линия

Редсток, Пашков, Корф, общество духовно-нравственного чтения, аристократические и городские круги. Это не баптизм в узком смысле, но важнейшая линия будущего евангельского христианства.

## 1884 — две развилки

1884 нужно писать как драматическую главу о попытке стать публичным братством:

- Ново-Васильевка — южная братская сеть;
- Петербург — попытка общеимперского евангельского собрания и полицейское вмешательство;
- смысл — община выходит в публичность, государство показывает границы.

## Имперский административно-полицейский слой

### 1879 — признание без свободы

Ограниченный правовой канал для баптистов: наставники, молитвенные места, метрические записи, губернаторский надзор. Не “свобода совести”, а управляемая терпимость.

### 1883 — правовой режим сектантов/раскольников

Нужно поднимать точные тексты. В production не писать по памяти.

### 1894 — штунда как административная опасность

Ключевой год: штунда оформляется как опасный ярлык. Под него могли попадать разные группы, включая баптистов. Здесь важно показать механизм расширительного ярлыка.

### 1905 — окно, но не победа

После 1905 года стало легче переходить и легализовываться, но местная бюрократия, полиция и военный контекст оставались сильными ограничителями.

### 1914–1917 — война и подозрение

Немецкое влияние, отказ от оружия, лояльность, “сектанты” и германофилия — отдельный слой. Не всякая община была пацифистской, не всякий баптист отказывался от службы, не всякое подозрение было фактом.

## Православие и баптисты

Не писать “война православия с баптистами” плоско. Нужно держать пять регистров:

1. **Родная среда** — ранние штундисты могли оставаться в православной обрядовой среде.
2. **Богословский спор** — крещение, церковь, таинства, предание, священство, иконы.
3. **Социальный страх** — разрушение приходской дисциплины, семьи, деревенского порядка.
4. **Административная практика** — миссионерские тексты + государственный надзор + полиция.
5. **Современный диалог** — социально-этическое сотрудничество без богословского слияния.

## Православные источники: как использовать

`Миссионерское обозрение`, миссионерские съезды, Дородницын, Рождественский, Боголюбов, Терлецкий, епархиальные ведомости — это золото для понимания православной оптики. Но это не нейтральная история баптистов.

Безопасная формула:

> Православная миссионерская литература показывает, как церковная сторона видела штундистов и баптистов: как богословский вызов, социальную опасность и проблему церковной дисциплины. Эти описания нужно сверять с баптистскими журналами, административными документами и местными делами.

## Case cards для глав

| Case | Где использовать | Что сверять |
|---|---|---|
| Павлов / Воронин / Амирханьянц | `goneniya-i-sovest` | воспоминания + административные документы |
| Штунда 1894 | `yuzhnaya-shtunda`, `goneniya-i-sovest` | правовой текст + православная полемика + баптистская реакция |
| Петербург 1884 | `dva-sezda-1884` | баптистская память + полицейские/государственные документы |
| Миссионерские съезды | `goneniya-i-sovest` | протоколы + журнальная реакция |
| ХМКК / РПЦ–РС ЕХБ | `posle-nochi` | официальные сообщения + богословские границы |

## Готовая тональность для статьи

> Для православной миссии баптисты были не только богословским оппонентом. Они казались симптомом распада старой приходской России: крестьянин читал Библию дома, спорил со священником, собирался вне прихода и выбирал общину добровольно. Поэтому спор о крещении быстро становился спором о народе, власти и совести.


## v29: углублённые case-study cards

### CaseStudy 1: `Миссионерское обозрение` 1896 — штунда как пастырско-миссионерская проблема

- Период: конец XIX века.
- Голос: официальный православный миссионерский журнал.
- Потенциальная польза: язык страха, пастырская стратегия, ранняя типология “штундистов”.
- Риск: полемическая оптика, болезненное смешение богословского спора и социальной опасности.
- Production wording: “Православная миссионерская печать видела в штунде не только богословское уклонение, но и угрозу приходской дисциплине”.
- Что сверить: баптистские/штундистские свидетельства, местные административные меры, конкретные губернии.

### CaseStudy 2: `Миссионерское обозрение` 1899 — Киевские собеседования и полемика о крещении

- Голос: православная миссионерская полемика.
- Польза: показывает, где шёл нерв спора: крещение детей, церковь, Писание, таинства, “простецы”, миссионерские беседы.
- Риск: источник может говорить “штундисты/баптисты/пашковцы” слишком обобщённо.
- Production wording: “В православной полемике вопрос крещения был не частной деталью, а границей между церковно-таинственным и евангельско-баптистским пониманием церкви”.

### CaseStudy 3: Дородницын — материалы как смесь документов и интерпретации

- Польза: большой документальный корпус о религиозно-рационалистическом движении на юге России.
- Риск: подбор и комментарии встроены в православно-миссионерскую рамку.
- Правило: использовать как источник документов и православной редакции, но не как одинокий суд над происхождением баптизма.

### CaseStudy 4: Кальнев / Буткевич — “немецкое” и “западное” как обвинительная рамка

- Польза: показывает анти-западный/анти-протестантский объяснительный язык.
- Риск: “немецкое происхождение” превращается в полемический ярлык.
- Production wording: “Православные авторы часто объясняли штундо-баптизм через немецко-протестантское влияние; современная серия должна признать реальные немецко-меннонитские контакты, но не сводить русское движение к внешнему импорту”.

### CaseStudy 5: современный диалог РПЦ и РС ЕХБ

- Польза: показывает, что после советского периода возможна публичная коммуникация, совместные социально-этические темы и институциональные встречи.
- Риск: не выдавать это за богословское единство.
- Production wording: “Современные встречи показывают не слияние традиций, а поиск языка сосуществования и сотрудничества там, где позиции могут совпадать социально, оставаясь различными богословски”.

## v29: карта напряжений

| Напряжение | Баптистская сторона | Православная сторона | Как писать |
|---|---|---|---|
| Крещение | вера и сознательное исповедание | таинство, церковная полнота, детокрещение | объяснить богословскую логику обеих сторон |
| Писание и Предание | акцент на Библии и личном чтении | церковное толкование, Предание, литургия | не карикатурить ни одну сторону |
| Приход и община | добровольное собрание верующих | приходская/территориальная церковность | показать социальный конфликт |
| Миссия | проповедь, кружки, чтение | “совращение” православных | отделить свободу совести от конфессиональной тревоги |
| Государство | право на собрания и исповедание | защита православного порядка в империи | связать с правом и полицией |

## v34: углубление православно-баптистского конфликта через конкретные узлы

### Узел A: `Миссионерское обозрение` 1899 — собеседование как жанр контроля

`Миссионерское обозрение` 1899 фиксирует сразу несколько важных вещей: «Киевские собеседования со штундистами», материалы из миссионерских летописей и беседу Д. Боголюбова со штундо-баптистами о крещении младенцев. Это ценно не как нейтральная стенограмма баптистской веры, а как свидетельство того, какие вопросы православная миссия считала самыми опасными и публично спорными.

**Что можно утверждать безопасно:** в конце XIX века православная миссия воспринимала штундо-баптистскую среду как предмет организованной полемики; особое внимание уделялось крещению, церковной власти, Писанию, иконам, почитанию святых, церковному преданию.

**Что нельзя утверждать без сверки:** что текст точно передаёт слова оппонентов; что баптистская сторона была едина; что все южнорусские штундисты уже были баптистами в строгом организационном смысле.

### Узел B: Боголюбов — православная полемика, которая слышит баптистские возражения

Боголюбов полезен не только как «обличитель». Его материалы важны потому, что он явно знает ход баптистских возражений: дом Стефана, крещение младенцев, связь крещения и возрождения, личная вера, церковь и предание. Это позволяет восстановить карту спора.

**Готовая формула для статьи:**

> В православной миссионерской литературе спор с баптистами часто сосредоточивался не на внешних обычаях, а на самом нерве церковности: кто имеет право толковать Писание, что делает крещение, где граница Церкви и может ли личная вера быть основанием для церковного членства.

### Узел C: Кальнев — “немцы и штундобаптизм” как рамка подозрения

Кальнев важен тем, что показывает один из обвинительных ходов православной полемики: связать штундо-баптизм с немецким/западным влиянием. Для серии это нужно использовать очень аккуратно. Немецкое влияние действительно было важным в южнорусском контексте, но формула «русский баптизм = немецкий импорт» слишком груба и источниково опасна.

**Безопасная формула:** немецкая колонистская и меннонитско-братская среда была одним из каналов влияния, но русское/украинское евангельское движение нельзя сводить к пассивному заимствованию; оно развивалось через местное чтение Писания, крестьянские сети, молитвенные собрания, социальную мобильность и внутренние поиски церковной жизни.

### Узел D: Дородницын и Рождественский — документальность внутри полемики

Дородницын и Рождественский ценны тем, что часто собирают факты, документы, наблюдения и ранние сведения о движении. Но они пишут внутри православно-миссионерской картины мира. Это значит: фактические детали нужно извлекать, но объяснительные схемы — проверять.

**Практическое правило:** если православный автор сообщает место, дату, имя, собрание, административный эпизод — заносить в ledger как проверяемый факт-кандидат. Если он объясняет духовную причину движения, моральное состояние участников или “истинную сущность секты” — заносить как православную интерпретацию, а не как факт.

### Узел E: современный диалог РПЦ–РС ЕХБ

Современные встречи 2012 и 2024 годов нельзя подавать как “сближение вероучения”. Это другой жанр: церковная дипломатия, общественные темы, семейная/нравственная повестка, социальное служение, межконфессиональные площадки. На фоне этого сохраняются серьёзные богословские различия: крещение, церковь, предание, священство, иконы, таинства.

**Готовая формула:**

> В XXI веке конфликтный язык имперской миссии не исчезает полностью из культурной памяти, но на официальном уровне всё чаще сменяется языком ограниченного сотрудничества: не единство вероучения, а совместные общественные темы при сохранении глубоких догматических различий.

## v34: где это вставлять в серию

- `Южная штунда` — православная миссия как ближайший внешний наблюдатель и оппонент.
- `Гонения и совесть` — переход от полемики к административной практике.
- `Короткое окно 1905–1929` — легализация не снимает православного и административного напряжения.
- `После ночи` — современный диалог, ХМКК, общественные вопросы, но без богословского слияния.

---

# V39 no-loss expansion — режим «ничего не урезать»

Этот раздел добавлен после замечания: **при консолидации нельзя терять факты, выводы, абзацы, оговорки и рабочие решения из предыдущих проходов**. Поэтому v39 — не краткая выжимка и не рекламный summary, а рабочий master-пакет: в нём должны сохраняться все проверенные линии исследования, но без расползания на сотни файлов.

Правило v39:

1. **Старые v1–v26 и round-файлы не импортируются в репозиторий как рабочая структура**, но считаются черновым архивом исследования, из которого нельзя выбрасывать подтверждённые выводы.
2. **Каждый факт переносится в один из 10 master-файлов**, а не в новый одноразовый файл.
3. **Ни один вывод не должен исчезать при укрупнении**: если вывод ещё не готов для статьи, он переносится в статус `LEAD`, `QUESTION`, `BIOCASE-D`, `MEDIA-GATE`, `ARCHIVE-REQUEST` или `DO-NOT-ASSERT-YET`.
4. **Не сжимать до тезисов там, где нужна аргументация**: важные спорные темы требуют абзацев, контраргументов, источниковой критики и плана проверки.
5. **Не превращать источники в “истину”**: баптистский, православный, советский, зарубежный, светский, архивный и семейно-мемуарный голоса должны быть разведены.


## V39: полный слой православия, администрации и баптистской идентичности

Этот блок нельзя сокращать до простой формулы “православные против баптистов”. Реальная картина сложнее.

### Православная среда как родная и конфликтная

Ранние штундисты и будущие баптисты часто выходили из православной социальной среды. Они не всегда сразу мыслили себя как отдельную конфессию. Чтение Библии, домашние собрания, песня, разговор о личном обращении и критика формального благочестия могли сначала существовать внутри привычного православного мира, но постепенно становились границей.

### Православная миссия как источник

`Миссионерское обозрение`, миссионерские съезды, Боголюбов, Дородницын, Кальнев, Буткевич и епархиальные ведомости нужны не для того, чтобы заимствовать их оценки, а чтобы увидеть:

- как православные миссионеры описывали опасность штунды и баптизма;
- какие аргументы использовали против крещения по вере;
- как связывали “сектантство” с немецким влиянием, социальной нестабильностью, отпадением от народа и ослаблением государства;
- как религиозный спор превращался в административный вопрос.

### Административный слой

1879, 1883, 1894, 1905 и 1914–1917 нельзя давать как голые даты. Их нужно раскрывать через вопрос: что мог делать конкретный верующий? мог ли он собираться, венчаться, крестить, воспитывать детей, регистрировать общину, иметь наставника, ездить с проповедью, печатать литературу?

### Сотрудничество и диалог

Современный диалог РПЦ и РС ЕХБ нельзя подавать ни как богословское единство, ни как предательство различий. Это отдельный слой: социально-этические темы, общественная площадка, ХМКК, общие заявления, встречи, но при сохранении богословских расхождений.

### Что нельзя потерять

- ранняя близость к православной среде;
- миссионерская полемика как важный источник, но источник с интересом;
- административная машина как отдельный актор;
- поздний диалог как неравный, сложный, осторожный и тематически ограниченный;
- различие между православной критикой, государственным запретом и баптистской внутренней памятью.


---

## V39. Расширение: биографические сцены внутри имперского слоя

Имперский слой нельзя писать только через указы и полемические книги. Его надо показывать через сцены, где закон и полемика входят в жизнь людей.

### Сцена 1. Дом Кальвейтов и маленький круг в Тифлисе

Эта ветвь важна не как готовая легенда, а как сцена рождения общины из домашнего пространства. Семья, молитва, несколько человек, разговоры о крещении и Писании — всё это лучше показывает ранний баптизм, чем абстрактная фраза “возникла община”.

**Что можно писать осторожно:** ранний тифлисский круг нужно описывать как семейно-домашнюю среду, вокруг которой формировалось баптистское самосознание на Кавказе.

**Что нельзя писать без проверки:** “именно так всё началось” в единственном числе; “Кальвейты основали русский баптизм”; “немецкая семья создала русское движение”.

### Сцена 2. Павлов и Иванов-Клышников

Это не только два имени в списке ранних деятелей. Это сюжет духовного поиска, молоканского фона, молодого чтения Писания, перехода к баптистскому крещению, миссионерских поездок, дружбы и будущих ссылок. Для статьи полезно писать их рядом, потому что биография здесь показывает сеть.

**Смысл для главы:** русский баптизм не был только imported doctrine; он проходил через людей, уже живших в религиозно активной среде, через чтение Библии, споры, дружбу и путешествия.

### Сцена 3. Южные крестьяне и штундистская сеть

Ратушный, Рябошапка, Основа и другие южные фигуры должны быть не только “пионерами”, а представителями деревенского, крестьянского, семейного и общинного слоя. Это помогает не свести историю к Петербургу и печати.

**Риск:** православные источники часто смешивали группы и использовали ярлык “штунда” расширительно; баптистские источники могли ретроспективно упорядочивать раннюю сложность. Поэтому каждая фамилия требует связки: местность — источник — конфессиональный статус — дата — кто это так назвал.

### Сцена 4. Женщины Петербургского круга

Ливен, Черткова, Гагарина, Пейкер и другие женщины петербургского евангельского круга не должны исчезать за Пашковым/Редстоком/Корфом. Они нужны для понимания дома как миссионерской инфраструктуры: собрания, гости, уроки, благотворительность, тюрьмы, больницы, письма, печать.

**Безопасная формула:** женские фигуры петербургского круга были не фоном мужского лидерства, а частью социальной и духовной инфраструктуры евангельского движения.

### Сцена 5. Православная миссия встречает живых людей, а не “тезисы”

`Миссионерское обозрение`, Дородницын, Боголюбов, Кальнев и другие православные источники надо читать так: они показывают, как православная миссия видела “сектантов”, какие аргументы считала важными, чего боялась, как пыталась спорить. Но за ярлыком “штундо-баптисты” стоят реальные люди и семьи. В статье надо показывать оба слоя: язык источника и человеческую реальность.


---

## [3] SOURCE: `baptists_v93/08-chronology-data-model-master.md`

# 08. Chronology and data model master

## Зачем нужна хронология

Серия не должна быть сухой таблицей, но без общей шкалы читатель потеряется. Лучшее решение: в каждой главе 3–7 якорных дат + отдельный master chronology ledger.

## Диапазоны глав

| Глава | Диапазон | Якоря |
|---|---|---|
| Пролог | 988–1867 | 988, 1499, XVI в., 1810-е, 1860-е |
| Ночь на Куре | 1867 | 20 августа 1867 |
| Южная штунда | 1860-е–1884 | 1860-е, 1870-е, 1884 |
| Петербургская линия | 1874–1909 | 1874, 1884, 1905, 1909 |
| Две развилки | 1884 | Ново-Васильевка, Петербург |
| Библия, песнь и печать | 1870-е–1929 | 1906, 1907, 1910, 1927 |
| Гонения и совесть | 1879–1917 | 1879, 1883, 1894, 1905, 1914 |
| Короткое окно | 1905–1929 | 1905, 1907, 1917, 1920-е, 1929 |
| Советская ночь | 1917–1944 | 1917, 1929, 1930-е, 1944 |
| ВСЕХБ 1944 | 1944–1959 | 1944, 1945, 1959 |
| Инициативная группа | 1959–1965 | 1959, 1961, 1963, 1965 |
| Подпольная печать | 1963–1991 | 1963, 1965, 1976, 1980-е, 1991 |
| После ночи | 1991–сегодня | 1991, 1997, 2012, 2022, 2024 |

## Frontmatter proposal

```yaml
title: "Гонения и совесть"
series: "baptisty-rossii"
series_order: 6
series_range: "1879–1917"
confidence: "mixed"
timeline_anchors:
  - year: 1879
    label: "Ограниченное признание баптистов"
    confidence: "A/B"
  - year: 1894
    label: "Штунда как административная опасность"
    confidence: "B"
  - year: 1905
    label: "Окно веротерпимости"
    confidence: "A/B"
```

## Event ledger fields

```csv
id,date_start,date_end,label,chapter,place,source_family,source_ref,confidence,notes
```

## Не делать

- Не ставить годы в каждый H1 механически.
- Не делать одну гигантскую timeline в начале каждой статьи.
- Не смешивать дату публикации источника и дату описываемого события.
- Не превращать позднюю память в дату события без проверки.

## Нужно сделать в сайте

- `ChapterSpine` на landing.
- Mini timeline внутри каждой главы.
- Полная хронология в `spravochnik`.
- Фильтр по source-confidence: primary / periodical / memory / contested.


---

## V33 update — советская хронология: минимальный обязательный каркас

Добавить в master chronology:

- **1944** — образование/оформление ВСЕХБ как послевоенного разрешённого союза евангельских христиан и баптистов.
- **1945** — расширение объединительной модели; пятидесятнический вопрос; первые номера `Братского вестника` как источник послевоенной публичной церковности.
- **1959/1960** — `Новое положение ВСЕХБ` и `Инструктивное письмо старшим пресвитерам`; начало кризисного узла.
- **13 августа 1961** — первое обращение инициативной группы / начало движения в памяти СЦ ЕХБ.
- **1962** — преобразование инициативной группы в Оргкомитет.
- **1963** — первый `Вестник спасения`; официальный пересмотр/съездовой ответ ВСЕХБ требует отдельной сверки.
- **1965** — оформление Совета церквей ЕХБ / новая стадия разделения.
- **1976** — переход/переименование самиздатного корпуса к `Вестнику истины`.
- **1989–1991** — позднесоветский выход из подпольной/контрольной модели, новые возможности печати и публичной памяти.
- **1990** — покаянно-самокритический слой ВСЕХБ/СЕХБ по документам 1960-х требует точного page-level подтверждения.

Каждое событие должно иметь поля: `date_precision`, `voice`, `source_status`, `confidence`, `needs_primary_scan`.


## V33: хронология lived religion событий

Добавить в chronology ledger не только правовые события, но и cultural/community markers:

- появление/распространение песенных сборников;
- запуск детских/молодёжных изданий;
- ключевые молодёжные съезды;
- периоды давления на религиозное воспитание детей;
- известные фото/архивные свидетельства богослужений и хоров;
- публикации самиздатных бюллетеней родственников узников.

Каждое событие получает поле `event_type`: `law`, `conflict`, `periodical`, `worship`, `family`, `education`, `social_service`, `media`, `archive_lead`.


## v36 — Биографические даты как слой хронологии

В master chronology надо добавить отдельный тип события: `bio_event`.

Примеры:

| date | person/family | event_type | chapter | status |
|---|---|---|---|---|
| 1871-04 | Василий Павлов | baptism / early membership | Ночь на Куре | `verify month/source` |
| 1871-10-31 | Василий Иванов-Клышников | baptism in Kura | Ночь на Куре | `church-source; verify primary` |
| 1886 | Иван Проханов | conversion | Библия, песнь и печать | `church-source` |
| 1887-01-17 | Иван Проханов | believer’s baptism | Библия, песнь и печать | `church-source` |
| 1964-02-23 | Совет родственников узников | organization founded | Подпольная печать | `multi-source; verify primary` |
| 1970 | Лидия Винс | elected chair / Council relatives | Подпольная печать | `secondary+church; verify documents` |
| 1962 | Аида Скрипникова | arrest for distributing poems | Инициативники / Самиздат | `DHI; verify court` |

Визуально это можно показать не отдельной «лентой великих людей», а боковыми `story nodes` внутри хронологии.

---

# V39 no-loss expansion — режим «ничего не урезать»

Этот раздел добавлен после замечания: **при консолидации нельзя терять факты, выводы, абзацы, оговорки и рабочие решения из предыдущих проходов**. Поэтому v39 — не краткая выжимка и не рекламный summary, а рабочий master-пакет: в нём должны сохраняться все проверенные линии исследования, но без расползания на сотни файлов.

Правило v39:

1. **Старые v1–v26 и round-файлы не импортируются в репозиторий как рабочая структура**, но считаются черновым архивом исследования, из которого нельзя выбрасывать подтверждённые выводы.
2. **Каждый факт переносится в один из 10 master-файлов**, а не в новый одноразовый файл.
3. **Ни один вывод не должен исчезать при укрупнении**: если вывод ещё не готов для статьи, он переносится в статус `LEAD`, `QUESTION`, `BIOCASE-D`, `MEDIA-GATE`, `ARCHIVE-REQUEST` или `DO-NOT-ASSERT-YET`.
4. **Не сжимать до тезисов там, где нужна аргументация**: важные спорные темы требуют абзацев, контраргументов, источниковой критики и плана проверки.
5. **Не превращать источники в “истину”**: баптистский, православный, советский, зарубежный, светский, архивный и семейно-мемуарный голоса должны быть разведены.


## V39: хронология должна хранить не только даты, но и людей

В master chronology нельзя ограничиться годами союзов и законов. Нужно добавлять параллельные линии:

1. событие;
2. документ;
3. человек/семья;
4. журнал/публикация;
5. фото/медиа;
6. степень уверенности;
7. конфликт голосов.

### Минимальные связки

- 1867 — Кура / Воронин / Кавказская ветвь / Кальвейты как семейный фон.
- 1860–1880-е — южная штунда / Ратушный / Рябошапка / Лисицын / немецко-меннонитский контакт.
- 1870–1900-е — Петербург / Пашков / Ливен / Черткова / Гагарина / Пейкер / домашние собрания.
- 1905–1917 — легализация, печать, съезды, молодёжь, `Баптист`, `Христианин`, `Утренняя Звезда`.
- 1929 — закон о религиозных объединениях и сворачивание окна.
- 1944 — ВСЕХБ.
- 1959–1965 — кризис, документы, инициативники.
- 1964–1987 — Совет родственников узников, бюллетени, семьи, дети, ходатайства.
- 1991–сегодня — постсоветская свобода, институционализация, диалог, новые вызовы.


---

## V39. BioChronology: даты людей рядом с датами законов

Хронология серии должна иметь два слоя:

1. **Public/legal chronology** — указы, съезды, журналы, объединения, расколы, документы.
2. **Human chronology** — обращения, крещения, высылки, письма, суды, рождения, смерти, семейные события, выпуск бюллетеней, похороны, эмиграции.

Иначе история будет выглядеть как история институтов, а не общин.

### Дополнительные поля для chronology ledger

```yaml
event_id:
date:
precision: exact / month / year / approximate
person_or_family:
event_type:
source:
confidence:
chapter:
human_meaning:
public_context:
```

### Пример связки

- 1894 как административный год важен сам по себе.
- Но рядом должны стоять личные последствия: запрет собраний, высылки, надзор, письма, поездки, семейные разрывы.

- 1959–1961 как документы ВСЕХБ и конфликт инициативников важны сами по себе.
- Но рядом должны стоять дети, молодёжь, воскресные школы, семьи, женщины Совета родственников, письма из тюрем.

Так хронология становится не таблицей дат, а картой давления и верности.
