# 05_REPO_MEDIA_INTEGRATION — TRUE GROUPED MASTER v98

**Назначение:** Интеграция в GitHub/серии, медиа, публикационный план.

**Правило v98:** это рабочий групповой файл. Новые находки добавлять сюда, а не создавать numbered MD. Каждый блок ниже сохраняет исходный путь, чтобы ничего не потерять.

## Быстрый состав группы

- `baptists_v93/06-foreign-archives-secular-media-master.md` (38186 bytes)
- `baptists_v93/07-media-photo-permissions-master.md` (21926 bytes)
- `baptists_v93/09-chapter-insertion-map-master.md` (39727 bytes)
- `baptists_v93/37-chapter-draft-public-square-v60.md` (37764 bytes)
- `baptists_v93/111-zip-and-repo-audit-v85.md` (6114 bytes)
- `baptists_v93/115-repo-integration-map-v85.md` (2358 bytes)
- `baptists_v93/120-repo-clean-integration-plan-v86.md` (2226 bytes)
- `baptists_v93/125-repo-v87-integration-warning.md` (2250 bytes)

---



---

## [1] SOURCE: `baptists_v93/06-foreign-archives-secular-media-master.md`

# 06. Foreign archives and secular media master

## Назначение

Зарубежные источники нужны не потому, что они “объективнее”, а потому что дают внешний угол: немецкий, американский, британский, европейский, миссионерский, правозащитный, журналистский, архивный.

## Немецкий слой

### Oncken-Archiv / BEFG

Золото для немецко-баптистской линии, Oncken-сети, немецкой периодики, переписки, фотографий, связей с Россией и Восточной Европой. Но не использовать как доказательство “немцы создали всё”.

### Pritzkau / German Baptists in South Russia

Близкий к первичному/мемуарно-историческому слой по немецким баптистам Южной России. Ценность высокая, но жанр не нейтрален.

### Немецкая периодика

`Der Wahrheitszeuge`, `Die Gemeinde`, материалы BEFG/Oncken — future search. Нужно искать связи с Russland, Südrussland, Mennoniten, Baptisten, Stundisten, Prokhanov, Pavlov, Oncken.

## Американский слой

### SBHLA Wardin AR 915

Один из главных архивных корпусов. Ценен не только текстами, но и leads по фотографиям: leaders, churches, women/family, worship, films, BWA, Rushbrooke, Prokhanov, KGB, Initiative Group, relatives of prisoners.

### Russian Evangelical Archives AR 881

Особенно важны:

- `Journal of the Baptist Union of the USSR`, 1925–1926;
- `Khristianin`, 1927;
- diary of Vasily Pavlov, 1910–1911;
- letters in the Council for the Affairs of Religious Cults, 1946–1961.

### BWA

BWA нужна для международной сцены: 1905 London, 1908 Berlin, 1911 Philadelphia, Russian delegation, Prokhanov, Rushbrooke, resolutions on religious freedom. Не превращать в “BWA сказала = истина”; это международно-баптистская оптика.

## Keston / Baylor

Золото для позднесоветского слоя: samizdat, petitions, letters, reports, `Vestnik spaseniia`, `Vestnik istiny`, subject files on unregistered Baptists. Но использовать как archive lead / source drawer, а не как свободный visual asset.

## Светские СМИ

### TIME 1929

Внешний снимок о советских анти-религиозных ограничениях и баптистах. Использовать как media-frame рядом с законом 1929 и академической проверкой.

### TIME 1972

Внешний взгляд на советских баптистов, регистрацию, раскол, репрессии. Опасно: может упрощать происхождение баптистов через западную миссию.

### Guardian 2007 / Крючков

Полезно для памяти о лидере Совета Церквей в западной прессе. Не заменяет внутренние источники.

### AP / Reuters / TIME 2024

Современный блок “После ночи”: Украина, война, религиозная свобода, оккупированные территории, транснациональная баптистская солидарность. Использовать как современный media-frame, сверять с Forum 18, USCIRF, IRFBA, украинскими источниками.

## Noise filter

Отбрасывать:

- блоговые пересказы без ссылок;
- “истории баптизма” без аппарата;
- статьи, где Россия/Украина/СССР смешаны без дат;
- фото без provenance;
- современные политические тексты, если они не дают проверяемого факта.

## Что добавить в главы

| Глава | Зарубежный слой |
|---|---|
| `yuzhnaya-shtunda` | Pritzkau + немецко-меннонитская проверка |
| `peterburgskaya-liniya` | Oncken / Radstock / Pashkov leads |
| `zolotoe-okno` | BWA, Coleman, международные съезды |
| `sovetskaya-noch` | TIME 1929 + правовой слой |
| `iniciativnaya-gruppa` | Keston/Baylor, samizdat |
| `podpolnaya-pechat` | `Vestnik spaseniia`, `Vestnik istiny`, relatives bulletins |
| `posle-nochi` | AP/Reuters/TIME + официальные баптистские/религиозно-свободные источники |


## v29: foreign deepening without file sprawl

### SBHLA AR 881 — почему это не просто lead

AR 881 особенно важен тем, что объединяет материалы, сканированные из Russian Evangelical Archives в Москве, и включает корпусные цели: журналы Союза баптистов СССР 1925–1926, `Христианин` 1927, дневник Василия Павлова 1910–1911, письма Совета по делам религиозных культов 1946–1961. Это не готовая цитата, но это дорожная карта к первичным документам.

### Baylor/Keston — late Soviet source drawer

Keston/Baylor нужно использовать в трёх слоях:

1. `Vestnik spaseniia` / `Vestnik istiny` как подпольная периодика.
2. Subject files как указатель дел, писем, петиций, судебных материалов.
3. Keston newsletters / finding aids как вторичный архивный контекст, а не как доказательство содержания каждого дела.

### Modern leads

Современные сообщения о запретах незарегистрированных баптистских общин в России могут быть важны для эпилога “После ночи”, но не должны смешиваться с историей имперского или советского периода. Любая современная новость получает статус `LEAD_ONLY` до сверки через Forum 18, судебные базы, местные документы и минимум один независимый источник.

## v29: secular media usage formula

> Светская зарубежная пресса показывает, как тема становилась видимой за пределами церковной среды. Она помогает понять международное восприятие, но не заменяет юридические документы, церковные журналы и архивные дела.

## v34: зарубежный и светский слой как контрольный контур, а не судья

Зарубежные архивы и светская пресса нужны не для того, чтобы заменить русские источники, а чтобы увидеть, что было заметно снаружи. TIME 1929 показывает западный пресс-фрейм вокруг советского ограничения религиозной жизни; TIME 1972 — западный образ советских баптистов и конфликта вокруг регистрации; Guardian 2007 — внешний некролог Крючкова; AP/TIME/Reuters 2024–2025 — современный публичный контекст войны, религиозной свободы и протестантских сетей.

### v34: три уровня использования светской прессы

1. **Frame evidence** — как тема описывалась вовне.
2. **Lead** — куда искать документы/архивы/имена.
3. **Corroboration only** — подтверждает, что событие было публично заметно, но не доказывает внутреннюю причинность.

### v34: нельзя делать

- Нельзя писать: “TIME доказал, что...”.
- Нельзя переносить Cold War language как нейтральное описание.
- Нельзя путать современную украинскую ситуацию, российские баптистские союзы, украинских баптистов и нерегистрированных советских баптистов как один сюжет.

### v34: полезная редакционная формула

> Зарубежная пресса не решает вопрос истины, но показывает, когда внутрироссийская история становилась международно видимой — в 1929 году вокруг советской антирелигиозной политики, в 1970-е вокруг нерегистрированных баптистов и самиздата, в XXI веке вокруг религиозной свободы, войны и публичной дипломатии церквей.


---

## V33 update — Baylor/Keston и светские СМИ для советского блока

### Baylor/Keston: не “готовая истина”, а архивный шлюз

Baylor/Keston records по `Vestnik istiny` и unregistered Baptists дают сильный доступ к самиздату и материалам о преследованиях. Их статус:

- **Tier A lead:** если record содержит PDF/full asset и метаданные выпуска;
- **Tier B context:** если record описывает collection/finding aid без конкретного листа;
- **Permission/rights check:** если нужны изображения или сканы для сайта.

Что проверять первым:

- `Vestnik istiny, No. 1 (53), 1976`;
- `Vestnik istiny, No. 2 (54), 1976`;
- `Vestnik istiny, No. 1 (61), 1978`;
- `Vestnik istiny, No. 2 (66), 1979`;
- `Vestnik istiny, No. 1 (93), 1986`;
- `Vestnik istiny, No. 3 (107), 1989`;
- `Soviet Union Unregistered Baptists Subject Files`.

### DHI Protestantizm: narrativized academic/public-history layer

DHI полезен как структурированный вторичный вход в 1959–1965: документы ВСЕХБ, реакция Крючкова/Прокофьева, Инициативная группа, Оргкомитет. Но для final-text DHI не должен заменять первичные послания и документы.

### Светские СМИ

TIME/Guardian/AP/Reuters полезны не как “объективный суд”, а как карта внешнего восприятия. Для советского блока TIME 1972 и Guardian/Kryuchkov obituary дают западную видимость конфликта и памяти. Для постсоветского/украинского блока AP/TIME/Reuters требуют отдельного геополитического контекста и не должны смешиваться с историей русского баптизма XIX века.

### Вставка в главы

- Глава 9: Baylor/Keston почти не нужен; там первичнее `Братский вестник` и государственные документы.
- Глава 10: DHI + первичные послания + Неволин/Никольская + Правэнц/РС ЕХБ.
- Глава 11: Baylor/Keston становится центральным внешним архивным шлюзом.
- Глава 12: СМИ и современные religious freedom reports использовать с явной маркировкой политического контекста.


## V33: зарубежные архивы как источник lived religion, а не только политики

SBHLA/Wardin и Mennonite Church USA Archives особенно ценны для визуального слоя повседневной общинной жизни: богослужения, хоры, рукописные песенники, советские общины, международные поездки и контакты.

### Mennonite Church USA Archives / Flickr Commons

Кадры Novosibirsk Baptist Church 1982 и related set важны как rare visual evidence late Soviet Baptist worship. Статус `No known copyright restrictions` не равен полной юридической гарантии: использовать после проверки страницы Commons/Flickr, original file, caption, source institution, and attribution.

### Wardin AR 915

Finding aid показывает, что коллекция содержит не только политико-правовые материалы, но и серии по биографиям, женщинам/семьям, worship, фотографии, films, Russian Baptists 1944–1988, Reform Baptists, Stundism, German Baptists, Mennonites. Это делает её одним из главных архивных путей к lived religion.

### Modern public ethics

Социальная концепция РС ЕХБ нужна в постсоветской главе как self-definition: свобода совести, права человека, ненасилие в выборе религии, сотрудничество с людьми доброй воли. Но это официальный нормативный текст, а не описание фактической практики всех общин.


---

## V33 addendum — зарубежные архивы для биографических ветвей

### Keston / Baylor

Keston/Baylor особенно важен для человеческого слоя позднего СССР: там искать не только общие отчёты о преследованиях, но и **case files** по семьям, детям, письмам, судебным процессам, женщинам Совета родственников узников, Аиде Скрипниковой, Винсам, материалам `Vestnik spaseniia` и `Vestnik istiny`.

Особенно важный узел: Совет родственников узников ЕХБ как женская/семейная правозащитная сеть. Внешние источники описывают его как организацию, которая собирала и распространяла сведения о репрессиях, а также помогала семьям заключённых.

### SBHLA / Wardin

Wardin AR 915 и AR 881 важны для биографий не только лидеров, но и региональных служителей, семей, фотографий, BWA-связей, русской эмиграции, женщин, молодежи и богослужений. В очередь на запрос поставить:

1. photos: leaders / churches / women and family / worship;
2. folders on Russian Baptist prisoners and Council of Relatives;
3. diaries and correspondence of Vasily Pavlov;
4. `Journal of the Baptist Union of the USSR` 1925–1926;
5. Russian Evangelical Archives biographical folders.

### Secular / Christian Western press

Christianity Today, TIME, congressional hearings, Keston newsletters, DHI case pages — полезны для того, как отдельные баптисты становились видимыми на Западе. Но это не заменяет внутренние документы. Например, история Винсов и Скрипниковой должна идти треугольником:

- внутренние документы СЦ ЕХБ / Совета родственников;
- Keston/Baylor / DHI / academic source;
- западная пресса / hearings как слой внешней огласки.

### Биографические leads для запроса

- Lydia Vins / Lidia Vins / Лидия Винс;
- Georgi Vins / Георгий Винс;
- Natalia Vins congressional testimony;
- Aida Skripnikova trial transcript;
- Council of Prisoners’ Relatives;
- Ulyana Germaniuk / Ульяна Германюк;
- Serafina Yudintseva / Серафина Юдинцева;
- Aleksandra Kozorezova / Александра Козорезова;
- Nikolai Khmara / Николай Хмара;
- children removed from Baptist families.


## v36 — Зарубежные архивы как источник биографических case files

Зарубежные архивы особенно полезны не тогда, когда дают общий обзор, а когда сохраняют конкретные человеческие следы:

- письма узников;
- списки арестованных;
- бюллетени родственников;
- фотографии семей и собраний;
- судебные протоколы, переданные за рубеж;
- правозащитную переписку;
- материалы международной кампании в защиту конкретного человека.

### Приоритетные зарубежные биографические ветви

| Архив / корпус | Биографическая ценность | Production status |
|---|---|---|
| Baylor/Keston — Unregistered Baptists Subject Files | дела и материалы по незарегистрированным ЕХБ, преследованиям, письмам, самиздату | `REQUEST-FIRST` |
| DHI Protestantizm | curated case pages: Аида Скрипникова, церковный конфликт, документы | `READY-AS-LEAD` |
| SBHLA AR 881 | дневник Павлова 1910–1911, `Journal of the Baptist Union of the USSR`, `Khristianin` 1927 | `REQUEST-FIRST` |
| SBHLA Wardin AR 915 | фото, региональные папки, женщины/семья/богослужение, BWA contacts | `REQUEST-FIRST` |
| Radio Liberty / Open Society / human rights channels | биографии, самиздат, международная огласка | `LEAD-ONLY` |
| KHPG / museum.khpg.org | биографические справки по правозащитникам и узникам | `USE-WITH-CHECK` |

### Как использовать западные биографические материалы

Не писать: «Западные источники доказали...»

Писать: «Эта судьба получила международную огласку; западные правозащитные и церковные каналы передавали такие-то сведения; для окончательной формулировки нужны советские судебные/архивные документы и самиздатный оригинал».

### Биография и международная огласка

Для позднесоветского периода отдельная тема: некоторые баптистские судьбы становятся известны миру не только потому, что они были важны внутри братства, но потому что их письма, стихи, судебные документы и бюллетени выходили наружу. Это особенно важно для:

- Аиды Скрипниковой;
- Лидии Винс;
- Георгия Винса;
- Николая Хмары;
- семей, у которых пытались отобрать детей;
- узников, чьи письма публиковались в бюллетенях.


---

## v36 — зарубежные архивы как BioCase-хранилища

Зарубежные архивы полезны не только для общей истории баптизма, но и для биографических ветвей. В них часто сохраняются письма, фотографии, машинописные отчёты, списки узников, обращения к западной общественности и эмигрантская память.

### SBHLA / Wardin / Russian Evangelical Archives

Для биографического прохода особенно важны:

- Wardin AR 915 — фото, correspondence, BWA, Rushbrooke, Prokhanov, Russian Baptist files, women/family/worship categories.
- Russian Evangelical Archives AR 881 — `Journal of the Baptist Union of the USSR`, `Khristianin`, diary/materials around Pavlov, correspondence and Soviet-era documents.
- AR 915-1 — отдельные папки по Russian Baptists / German Baptists / Mennonites / BWA / persecution / family and worship.

Задача агента: не скачивать всё, а запросить/вытащить **case files** по именам: Pavlov, Voronin, Ivanov-Klyshnikov, Prokhanov, Vins, Khmara, Skripnikova, Council of Prisoners' Relatives.

### Baylor/Keston

Baylor/Keston особенно важен для позднесоветских биографий:

- `Vestnik istiny` records;
- `Vestnik spaseniia` records;
- subject files on unregistered Baptists;
- correspondence / petitions / samizdat;
- links to British Christian/public pressure around Aida Skripnikova and Council of Churches.

Keston нельзя читать как «нейтральный суд». Это правозащитный и исследовательский архив с собственной холодновоенной и religious-freedom рамкой. Но именно поэтому он ценен как внешний слой к советским документам и баптистскому самиздату.

### DHI Protestantizm

DHI полезен для curated case studies, особенно по:

- Инициативной группе;
- Аиде Скрипниковой;
- письмам, самиздату и британской общественности;
- конфликту 1959–1965;
- документам 1959/1960.

Но DHI — входная витрина. Для финального текста желательно опускаться до документа/страницы/архива.

### Секулярные СМИ

TIME/Guardian/AP/Reuters и другие светские СМИ не дают «истину о баптистах», но дают внешний снимок:

- как Запад видел советских баптистов;
- какие имена становились публичными;
- какие сюжеты попадали в human-rights рамку;
- как религиозное преследование связывалось с Хельсинки, холодной войной, Украиной, свободой совести.

Для биографий это полезно как `external reception layer`: не вместо самиздата и архивов, а рядом с ними.


---

## v36 — Зарубежные архивы как хранилища биографических case files

Зарубежные архивы нужны не только для общего фона. Их главная ценность для следующего этапа — **case files**: письма, фотографии, списки, судебные документы, самиздат, биографические материалы.

### Лучшие направления

- **SBHLA / Albert Wardin Russian Baptists Collection.** Имеет биографическую серию и материалы по Russian/Eastern European Baptists. Использовать как roadmap к людям и папкам, а не как готовый текст.
- **Russian Evangelical Archives AR 881.** Важен для дневников, журналов, писем и редких материалов вроде дневника Павлова и журналов 1920-х.
- **Baylor/Keston.** Особенно важен для Совета церквей, Совета родственников узников, Аиды Скрипниковой, фотографий, самиздата, trial transcripts.
- **DHI Protestantizm.** Сильный цифровой проект для вводной навигации по инициативникам, детям, Аиде Скрипниковой, разделению 1959–1965; но всегда сверять с первичными документами.
- **Правозащитные архивы Украины / KHPG.** Полезны для Лидии Винс, Совета родственников и отдельных семейных историй.

### Новые targets v36

- Baylor/Keston: `Photographs of Soviet Unregistered Baptist Believer Aida Skripnikova` — потенциально сильный визуальный BioCase, но production только после прав/атрибуции.
- KHPG: Council of Relatives — использовать для структуры женского правозащитного служения и смены руководства после эмиграции Лидии Винс.
- CEU thesis по Георгию Винсу — использовать как вторичный аналитический источник по совести/гражданскому неповиновению, не как первичный документ.
- Religious samizdat / Human Rights Advocacy — использовать для описания того, как женщины и ordinary members стали видимыми через самиздат и западную огласку.


## V39 deepening — зарубежные архивы как хранилища BioCase, а не только общей истории

### Baylor / Keston

Baylor/Keston нужен не просто для общей фразы «на Западе знали о преследовании». Его главная ценность — case files:

- Aida Skripnikova trial / poem / street witness;
- Lidia Vins / Georgi Vins / family correspondence;
- Council of Relatives of Prisoners;
- children of ECB prisoners;
- lists of prisoners;
- unregistered Baptist trial materials;
- Keston newsletters and campaign materials.

Особенно важный тип источника — не публикация, а **архивная единица**: folder, box, item. В статье нельзя писать «Keston говорит», если реально использован только finding aid. Нужно писать: `Keston finding aid points to...`, пока нет конкретного документа.

### Amnesty / secular human-rights notices

Amnesty materials полезны для внешней реакции на отдельных людей, например Аиду Скрипникову. Но это внешний advocacy-текст, который может усиливать драматизм. Использовать так:

- как свидетельство международной видимости дела;
- как lead к судебным документам;
- как показатель того, что советский локальный конфликт стал международным;
- не как единственный источник фактов биографии.

### SBHLA / Wardin / Russian Evangelical Archives

Использовать для:

- семей Винс;
- Баптистского союза СССР 1920-х;
- дневника Павлова 1910–1911;
- международных контактов;
- фото и региональных документов.

### DHI Protestantizm

DHI особенно полезен для готовых тематических входов: Aida, Children, Church, Initiative group. Но DHI — вторичный digital humanities ресурс. Он нужен как карта и комментарий, а не замена первичным текстам.

---

# V39 no-loss expansion — режим «ничего не урезать»

Этот раздел добавлен после замечания: **при консолидации нельзя терять факты, выводы, абзацы, оговорки и рабочие решения из предыдущих проходов**. Поэтому v39 — не краткая выжимка и не рекламный summary, а рабочий master-пакет: в нём должны сохраняться все проверенные линии исследования, но без расползания на сотни файлов.

Правило v39:

1. **Старые v1–v26 и round-файлы не импортируются в репозиторий как рабочая структура**, но считаются черновым архивом исследования, из которого нельзя выбрасывать подтверждённые выводы.
2. **Каждый факт переносится в один из 10 master-файлов**, а не в новый одноразовый файл.
3. **Ни один вывод не должен исчезать при укрупнении**: если вывод ещё не готов для статьи, он переносится в статус `LEAD`, `QUESTION`, `BIOCASE-D`, `MEDIA-GATE`, `ARCHIVE-REQUEST` или `DO-NOT-ASSERT-YET`.
4. **Не сжимать до тезисов там, где нужна аргументация**: важные спорные темы требуют абзацев, контраргументов, источниковой критики и плана проверки.
5. **Не превращать источники в “истину”**: баптистский, православный, советский, зарубежный, светский, архивный и семейно-мемуарный голоса должны быть разведены.


## V39: зарубежные архивы и светские СМИ без потери контекста

Зарубежные источники нужны не как “истина снаружи”, а как дополнительный угол зрения. В v39 сохраняется вся логика предыдущих проходов:

### Немецкий слой

Oncken-Archiv, немецко-баптистская периодика, Pritzkau, немецко-меннонитские связи, Южная Россия, немецкие колонисты. Этот слой помогает увидеть баптизм в международной сети, но не должен превращать русско-украинское движение в простой немецкий импорт.

### Американский слой

SBHLA/Wardin AR 915 и Russian Evangelical Archives AR 881 особенно ценны как case-file хранилища: биографии, фото, письма, журналы, материалы BWA, дневник Павлова, Russian Delegation, Prokhanov, Rushbrooke, Baptist World Alliance. Их нельзя использовать как production source без запроса/проверки, но нельзя и потерять.

### Keston/Baylor

Keston/Baylor — ключевой внешний архив позднесоветской религиозной свободы, самиздата, писем, преследований, фотографий, бюллетеней и case files. Он особенно важен для Скрипниковой, Винсов, инициативников, Совета родственников, детей верующих, судов и международной огласки.

### Светская пресса

TIME, Guardian, AP, Reuters, Le Monde, Die Zeit, The Times, Manchester Guardian — это media snapshots. Их ценность в том, что они показывают, как тема звучала в нерелигиозном публичном пространстве. Их риск — упрощения, холодновоенная рамка, журналистская драматизация, политический контекст.

### Не терять “lead-only”

Если источник не готов для статьи, он не исчезает. Он получает статус:

- `LEAD-ONLY` — найдено направление, нужен доступ;
- `ARCHIVE-REQUEST` — нужен запрос в архив;
- `PERMISSION-GATE` — есть медиа, но права не ясны;
- `QUOTE-CHECK` — есть цитата/пересказ, нужен оригинал;
- `CASE-FILE` — возможно дело конкретного человека.


---

## V39. Зарубежные архивы как хранилища биографических дел

Зарубежные архивы важны не только как “внешнее подтверждение”, а как места, где сохранялись конкретные человеческие дела: письма, фотографии, списки заключённых, судебные материалы, обращения, отчёты, некрологи, кампании Amnesty, Keston notes, BWA correspondence.

### Что искать по каждому архиву

| Архив / корпус | Биографический потенциал | Риск |
|---|---|---|
| Baylor/Keston | суды, самиздат, `Vestnik istiny`, письма, dossiers по unregistered Baptists | finding aid не заменяет просмотр дела |
| SBHLA Wardin AR 915 | фото, переписка, BWA, Russian Baptists, women/family, worship, films | нужен запрос/права/контекст |
| Russian Evangelical Archives AR 881 | дневник Павлова, `Journal of the Baptist Union`, `Khristianin`, письма 1946–1961 | без просмотра нельзя цитировать содержание |
| Amnesty archives | внешняя правозащитная огласка конкретных узников | кампания не доказывает все детали дела |
| DHI Protestantizm | структурированные биографические очерки и тематические разделы | цифровой вторичный entrance, требует сверки |
| Guardian/TIME/AP/Reuters | внешнее восприятие, obituary, современный media-frame | журналистский жанр, геополитическая рамка |
| Oncken-Archiv | немецкая баптистская сеть, переписка, периодика, возможно Кавказ/Юг | немецкоцентричная рамка |

### Биографические сюжеты для зарубежного поиска

1. **Георгий Винс** — семья, отец Пётр Винс, лагерная память, секретарь СЦ ЕХБ, обмен/эмиграция, тексты, международные связи.
2. **Лидия Винс** — мать, руководитель Совета родственников, письма, ходатайства, международная защита.
3. **Аида Скрипникова** — суд, стихи, молодёжь, передача материалов иностранцам, Amnesty/Keston.
4. **Ульяна Германюк** — семья, ссылка, суд, болезнь, некролог, женская репрезентация в самиздате.
5. **Зинаида Вильчинская / Маргарита Готман / Андрусенко / Крючкова** — поздний советский слой перевозки документов, машинок, материалов Совета родственников.
6. **Павлов** — diary/letters, early Baptist network, exile, publications.
7. **Пашковская сеть** — London/German/English connections, Radstock, BWA-adjacent perception.

### Safe sentence для зарубежных источников

> Зарубежные архивы показывают, какие материалы о советских и российских баптистах циркулировали за пределами СССР/России. Они не отменяют необходимость проверки внутри русскоязычных источников, но помогают увидеть международную видимость конкретных судеб.


---

## [2] SOURCE: `baptists_v93/07-media-photo-permissions-master.md`

# 07. Media, photo, permissions master

## Принцип

Фото — не украшение, а источник. Но фото легко переподписать, вырвать из контекста, ухудшить, очистить до потери смысла или использовать без прав.

## Три версии изображения

| Версия | Что это | Где хранить |
|---|---|---|
| `original` | скачанный архивный оригинал без изменений | `public/images/baptisty-rossii/originals/` или research-only |
| `restored` | очищенная/улучшенная версия | `public/images/baptisty-rossii/restored/` |
| `generated` | художественная реконструкция / DALL-E | `public/images/baptisty-rossii/generated/` |

Нельзя выдавать `restored` или `generated` за архивный оригинал.

## Что можно улучшать

Можно:

- убрать пыль/царапины;
- поднять резкость осторожно;
- убрать современные водяные знаки, если есть право использовать оригинал;
- восстановить контраст;
- подготовить 16:9 обложку из архивного материала с явной пометкой.

Нельзя:

- менять лица;
- дорисовывать людей как будто это архивный факт;
- удалять исходный журнальный текст с факсимиле;
- делать “чистое фото” из страницы журнала и скрывать источник;
- использовать современные фото со СМИ без прав.

## Подпись к фото

Каждая подпись должна иметь:

- кто/что;
- где;
- дата или диапазон;
- источник;
- статус прав;
- уровень уверенности;
- если cleaned/restored — пометка.

Пример:

> Санкт-Петербургский юношеский кружок евангельских христиан, 1907. Источник: `Братский листок`, приложение к `Христианину`; скан через Wikimedia Commons. Подпись с идентификацией Проханова требует сверки по выпуску. Restored version based on original scan.

## Curated production candidates

| ID | Что | Использование | Статус |
|---|---|---|---|
| Prokhanov portrait / sermon 1924 | Проханов | Петербург / печать | проверить rights, вероятно PD по старым журналам |
| Pavlov 1925 | Павлов | Кура / ранние лидеры | Commons PD, проверить оригинал |
| Youth circle 1907 | юношеский кружок | Петербург | Commons, проверить подпись |
| Youth congress 1909/1910 | молодёжь | короткое окно | Commons, page-check |
| Voronezh sisters 1927 | женщины/труд | lived religion | Commons, page-check |
| Vifania 1928 | трудовая коммуна | социальное служение | Commons, page-check |
| Bratsky Vestnik 1945 | ВСЕХБ | послевоенный слой | факсимиле/evidence card |
| Vestnik spaseniia cover | подполье | инициативники | Commons/Baylor, проверить права |
| Novosibirsk 1982 | богослужение | поздний СССР | NKCR/Flickr Commons, осторожно |
| SBHLA churches/leaders | архивы | фотоархив | permission gate |

## Permission gates

| Источник | Gate |
|---|---|
| Wikimedia Commons PD-old/PD-RusEmpire | можно после проверки страницы файла и hash |
| Flickr Commons NKCR | можно осторожно, с attribution и ledger |
| SBHLA | archive request / permission |
| Oncken-Archiv | archive request / permission |
| Baylor/Keston | читать terms, часто lead-only |
| Современные СМИ | не брать картинки без лицензии |
| РС ЕХБ / РПЦ современные фото | lead-only до разрешения |

## Image ledger required fields

```csv
id,title,date,source_page,download_url,source_publication,rights,status,chapter,use_type,overlay_notes,confidence,action
```

## Production workflow

1. Добавить candidate в ledger.
2. Проверить страницу файла и источник.
3. Скачать original.
4. Посчитать hash.
5. Сделать визуальный audit: надписи, водяные знаки, качество, лица, cropping.
6. Решить: `facsimile`, `photo`, `hero-source`, `evidence-card`, `lead-only`.
7. Только потом делать restoration.

## v34: фото по православно-баптистскому диалогу и полемике

Для этой темы почти все современные изображения имеют статус `LEAD-ONLY` или `PERMISSION-NEEDED`:

- фото встреч РПЦ/РС ЕХБ 2012 и 2024;
- фото ХМКК;
- изображения с patriarchia.ru / mospat.ru / baptist.org.ru;
- сканы современных статей и медиа.

Их нельзя автоматически класть в production. Для сайта лучше использовать:

1. старые public-domain обложки/страницы журналов (`Миссионерское обозрение`, `Баптист`, `Христианин`), если права и сканы подтверждены;
2. нейтральные архивные документы/периодику вместо современных пресс-фото;
3. собственные схемы: “карта напряжений”, “три голоса источников”, “полемика → администрация → диалог”.

### v34: лучший визуальный ход

Для православно-баптистского блока лучше не ставить фото современного рукопожатия как главный образ. Оно визуально создаёт ложный вывод о примирении/слиянии. Лучше использовать композицию из трёх источников:

- православная миссионерская страница;
- баптистская журнальная страница;
- административный документ / закон / хронологическая карточка.

Это честнее: тема не про “дружбу” и не про “войну”, а про долгую историю границ, споров, давления и ограниченного сотрудничества.


## V33: новые визуальные приоритеты

Визуальный отбор теперь должен перестать быть «портреты лидеров + обложки журналов». Для серии о баптистах России нужны четыре визуальных слоя:

1. `leaders` — Воронин, Павлов, Проханов, Каргель, Мазаев, Крючков и др.
2. `print culture` — журналы, обложки, страницы, песенники.
3. `lived religion` — собрание, хор, молитва, семья, дети, рукописные песенники.
4. `archive conflict` — документы, бюллетени, письма, самиздат, материалы родственников узников.

### Production rule

Фотографии с Commons/Flickr NKCR можно использовать только после evidence card:

- source page;
- original URL;
- institution;
- date/caption;
- rights field;
- visual verification;
- crop/restoration note;
- attribution string.

Restored/AI-cleaned versions never replace original. Store originals and derivatives separately.


---

## V33 addendum — фото и биографические ветви

Для биографий нужны не просто “красивые лица”, а доказательные визуальные карточки.

### Типы фото

1. **Портрет** — лидер/сестра/узник/служитель. Риск: ретушь, неверная подпись, поздний источник.
2. **Семейное фото** — показывает семейную ветвь, но требует осторожности с частностью и правами.
3. **Групповое фото общины** — полезно для атмосферы, но нельзя подписывать всех без подтверждения.
4. **Фото журнала/обложки** — безопаснее для раннего public-domain корпуса, но всё равно нужна страница источника.
5. **Фото суда/узников/самиздата** — часто rights-sensitive, использовать как lead до permission.

### Новые приоритеты media-ledger

- Martin Kalweit / Lena Kalweit / Tiflis Baptist beginnings — искать немецкие и РС ЕХБ leads;
- Ratushny / Pavlov / Lisitsin group portrait — уже есть Commons-lead, проверить оригинал `Слово Истины` 1914;
- Prokhanov family / Pashkov household — искать осторожно, не подменять семейную сцену поздней иконографией;
- Lydia Vins — искать Keston/Baylor/Wardin/Commons/US hearing materials;
- Aida Skripnikova — DHI/Keston image rights likely restricted; lead-only;
- Council of Relatives bulletin covers — public-domain/ineligible claims проверять отдельно;
- Novosibirsk Baptist Church 1982 worship and choir — Commons + Mennonite Church USA Archives; evidence-card required.

### Запрет

Не использовать AI-restored портрет как исторический источник. Можно использовать только как иллюстрацию после подписи: `реставрированная версия на основе ...`, а оригинал хранить рядом.


## v36 — Фото как биографическая ветвь, а не украшение

Для биографических глав фото нужно использовать не как «портрет для красоты», а как evidence object.

### Типы биографических изображений

| Тип | Пример | Как использовать |
|---|---|---|
| Портрет служителя | Павлов, Иванов-Клышников, Проханов, Крючков, Винс | только с датой/источником/правами |
| Семейное фото | семья Винс, семьи узников, домашние собрания | осторожно: не превращать частное фото в символ всей эпохи |
| Групповое собрание | молодёжные съезды, хоры, богослужение | подписи проверять по журналу/архиву |
| Обложка бюллетеня | Совет родственников, `Вестник истины` | хорошо для самиздатного блока, но права/источник отдельно |
| Письмо / судебный документ | узники, ходатайства, ответы властей | идеальный evidence object, но требует page-level citation |
| Детская/семейная сцена | воскресная школа, дети верующих, изъятия детей | высокая чувствительность, нужна проверка и этический фильтр |

### Правило original/restored для биографий

- `original/` — только исходник с архивной подписью и URL.
- `restored/` — только производная версия, если есть право и рядом сохранён original.
- `article/` — только после evidence card.

Нельзя делать AI-restoration так, чтобы лицо стало «лучше», но исторически менее надёжным. Для портретов допустимы чистка пыли, контраст, кадрирование; недопустимы «улучшенные» глаза/улыбка/возраст/одежда.


---

## v36 — Фото и биографии: не иллюстрация, а доказательная карточка

Для биографических ветвей фото особенно соблазнительно: лицо сразу делает историю живой. Но фото нельзя использовать как «украшение без источника».

### Правило BioPhoto

Каждое фото человека/семьи должно иметь:

```yaml
BioPhoto:
  person_or_family: ""
  source_page: ""
  archive_or_publisher: ""
  original_context: "journal issue / archive item / Flickr/Commons page / Baylor item"
  date_claim: ""
  caption_claim: ""
  rights_status: "PD | NKCR | permission-needed | unknown"
  article_use: "hero | inline | evidence-card | do-not-use-yet"
  restoration_allowed: "yes/no/only derivative"
```

### Важные кандидаты v36

- Aida Skripnikova photographs — Baylor/Keston item, **permission/rights gate**.
- Lidia Vins / Council of Relatives — искать оригинал фото и подпись, не брать из случайных сайтов.
- Novosibirsk Baptist Church 1982 — хороший lived religion photo, но не биография отдельного человека.
- Prokhanov / Pavlov / Ratushny / Kargel portraits — лучше брать из журналов/Commons с привязкой к выпуску и странице.
- Гагарина/Ливен/Черткова — искать портреты отдельно, но не использовать без прав и source chain.

### Нельзя

- брать фото из соцсетей как production;
- улучшать лица через AI без сохранения оригинала;
- подписывать человека уверенно, если подпись идёт только из позднего сайта без скана источника;
- смешивать restored photo с первичным документом.

---

# V39 no-loss expansion — режим «ничего не урезать»

Этот раздел добавлен после замечания: **при консолидации нельзя терять факты, выводы, абзацы, оговорки и рабочие решения из предыдущих проходов**. Поэтому v39 — не краткая выжимка и не рекламный summary, а рабочий master-пакет: в нём должны сохраняться все проверенные линии исследования, но без расползания на сотни файлов.

Правило v39:

1. **Старые v1–v26 и round-файлы не импортируются в репозиторий как рабочая структура**, но считаются черновым архивом исследования, из которого нельзя выбрасывать подтверждённые выводы.
2. **Каждый факт переносится в один из 10 master-файлов**, а не в новый одноразовый файл.
3. **Ни один вывод не должен исчезать при укрупнении**: если вывод ещё не готов для статьи, он переносится в статус `LEAD`, `QUESTION`, `BIOCASE-D`, `MEDIA-GATE`, `ARCHIVE-REQUEST` или `DO-NOT-ASSERT-YET`.
4. **Не сжимать до тезисов там, где нужна аргументация**: важные спорные темы требуют абзацев, контраргументов, источниковой критики и плана проверки.
5. **Не превращать источники в “истину”**: баптистский, православный, советский, зарубежный, светский, архивный и семейно-мемуарный голоса должны быть разведены.


## V39: медиа и фото — сохранять leads, но не тащить в production без проверки

Фото и обложки нельзя сокращать до “есть картинка”. Для каждого изображения нужно сохранять полный контекст:

- кто или что изображено;
- откуда изображение;
- дата;
- оригинальная подпись;
- размер/качество;
- статус прав;
- можно ли использовать в статье;
- нужно ли восстановление;
- что нельзя дорисовывать/искажать.

### Original / Restored / Derivative

Всегда разделять:

- `original` — скачанный оригинал или архивная копия;
- `restored` — чистка пятен, контраста, шумов;
- `derivative` — обрезка, коллаж, цветизация, реконструкция;
- `AI-generated` — только как иллюстрация, не как документ.

### Биографические фото

Для лиц особенно строгий режим:

- не использовать без подписи;
- не подписывать портрет как конкретного человека, если источник не подтверждает;
- не делать “реставрацию”, которая меняет лицо;
- если фото семейное/детское/узников — проверять этику и права;
- современные фото встреч РПЦ/РС ЕХБ/ХМКК — только после permission gate.

### Что нельзя потерять из media leads

- Ратушный, Павлов, Прокханов, Каргель, съезды молодёжи, `Утренняя Звезда`, `Молодой виноградник`, `Бюллетень Совета родственников`, Новосибирская баптистская церковь 1982, хор с рукописными песенниками, DHI/Keston photos, Baylor/Keston records, SBHLA photo folders.


---

## V39. BioPhoto no-loss policy

Биографические ветви почти неизбежно требуют лиц: портреты служителей, групповые фото, семьи, хоры, дети, узники, суды, сканы бюллетеней. Но именно здесь риск максимальный.

### Принцип

Фото человека не является просто иллюстрацией. Оно является утверждением:

- это именно этот человек;
- в это время;
- в этом месте;
- из этого источника;
- с такими правами;
- в таком жанре.

Если хотя бы один элемент неизвестен, фото получает статус `MEDIA-GATE`, а не `READY`.

### BioPhoto card

```yaml
media_id:
person_or_group:
claimed_date:
claimed_place:
source_page:
original_file:
rights:
caption_source:
identity_confidence:
production_status: READY / USE_AFTER_CHECK / MEDIA-GATE / ARCHIVE-REQUEST / DO-NOT-USE
restoration_allowed:
restoration_rules:
article_caption_safe:
article_caption_forbidden:
```

### Что нельзя делать

- Нельзя брать современный скан/фото из статьи просто потому, что оно “гуляет в интернете”.
- Нельзя AI-cleaned портрет подавать как архивный оригинал.
- Нельзя заменять неизвестное фото “похожим баптистом”.
- Нельзя ставить фото семьи/детей/узников без прав и без контекста.
- Нельзя использовать изображения из современных СМИ без отдельного права или честного external-link mode.

### Что можно

- Использовать старые public-domain журнальные обложки после проверки страницы/прав.
- Использовать Commons/архивные фото после проверки original file, license, caption и source publication.
- Делать restored-версию только рядом с original и с явной пометкой `restored derivative`.
- Для неопубликованных архивов — хранить lead и request text, не скачивать в production.


---

## [3] SOURCE: `baptists_v93/09-chapter-insertion-map-master.md`

# 09. Chapter insertion map master

## Пролог: До Куры

**Добавить:** долгий вопрос Писания, совести, церковно-государственного порядка, молокан и водных молокан.  
**Не делать:** протобаптистскую генеалогию от Руси.

Evidence cards:

- Библия/перевод/книжность;
- Russian Bible Society / переводческий мост;
- молоканская среда как переходный узел.

## 1. Ночь на Куре

**Добавить:** 1867 как точку кристаллизации, но не миф одиночного рождения.  
**Проверить:** Воронин, крещение, дата, кто свидетельствует, позднейшие формулы.

## 2. Южная штунда

**Добавить:** немецкие колонии, меннониты, меннонитские братья, штунда, молокане.  
**Не смешивать:** штунда ≠ баптизм автоматически.

Evidence cards:

- православное описание штунды;
- баптистское самоописание;
- Pritzkau / немецкая линия как внешний слой.

## 3. Петербургская линия

**Добавить:** Редсток, Пашков, Корф, городская евангельская среда, молодёжные кружки.  
**Фото:** юношеский кружок 1907, но подпись сверить.

## 4. Две развилки 1884

**Добавить:** Ново-Васильевка + Петербургский срыв.  
**Смысл:** братство пытается стать публичным; государство показывает границу.

## 5. Библия, песнь и печать

**Добавить:** `Баптист`, `Христианин`, `Утренняя звезда`, песни, издательство, журнал как братская инфраструктура.  
**Визуал:** факсимиле `Баптист` 1907 №1/2.

## 6. Гонения и совесть

**Добавить:** 1879, 1883, 1894, 1905, православная миссия, полиция, ссылка, военное подозрение.  
**Тон:** не “православные злодеи”, а механизм церковь–государство–приход–совесть.

## 7. Короткое окно 1905–1929

**Добавить:** легализация, рост, молодёжь, журналы, трудовые/социальные формы, 1929 как обрыв.  
**Визуалы:** Воронежские сёстры, Вифания, молодёжные съезды.

## 8. Советская ночь

**Добавить:** 1929, 1930-е, разрушение легальных сфер, repression without simplifying every detail.  
**Источник:** советские документы + баптистская память + внешняя пресса.

## 9. ВСЕХБ 1944

**Добавить:** контекст войны, объединение ЕХ и баптистов, разрешённая форма, Братский вестник.  
**Не делать:** простую формулу “компромисс = предательство”.

## 10. Инициативная группа

**Добавить:** 1959–1965, уставные ограничения, детское/молодёжное служение, регистрация, Совет Церквей.  
**Источник:** Keston/Baylor + внутренние документы + официальная линия ВСЕХБ.

## 11. Подпольная печать

**Добавить:** `Вестник спасения`, `Вестник истины`, бюллетени родственников, печатный риск, самиздат.  
**Визуал:** cover/facsimile, не современный коллаж.

## 12. После ночи

**Добавить:** 1991, закон 1997, постсоветская память, диалог с РПЦ, Украина/война/религиозная свобода, архивизация.  
**Не делать:** политический памфлет. Использовать как современный слой осведомлённости.

## Справочник / Атлас

Сюда выносить:

- полную хронологию;
- source ledger;
- media ledger;
- все спорные формулы;
- карты;
- архивные leads;
- список “что ещё не проверено”.


## v34: куда вставлять новые углубления

| Материал | Глава | Формат вставки | Ограничение |
|---|---|---|---|
| `Миссионерское обозрение` 1896 | `Гонения и совесть` | source drawer + 1 абзац о православной оптике | не цитировать как нейтральную историю |
| `Миссионерское обозрение` 1899 | `Библия, песнь и печать` / `Гонения и совесть` | evidence card о полемике крещения | сверить страницы |
| Дородницын | `Южная штунда` | документальная рамка + caveat | не делать единственным источником |
| Кальнев/Буткевич | `Южная штунда` | “обвинительная рамка немецкого влияния” | не принимать язык автора как итоговую формулу |
| AR 881 / Павлов diary | `Гонения и совесть` | архивный lead к case card | нужен доступ/скан |
| Keston / `Vestnik istiny` | `Подпольная печать` | source drawer + samizdat card | проверить условия download/use |
| Современные запреты/дела | `После ночи` | отдельный эпилогический блок | не смешивать с СССР/империей |

## v34: точечные вставки по православно-баптистскому блоку

### `2. Южная штунда`

Вставить подглаву: **“Православный взгляд: почему штунда стала тревогой”**. Там показать `Миссионерское обозрение`, Рождественского, Дородницына, но с дисклеймером жанра.

### `6. Гонения и совесть`

Вставить блок: **“От спора к надзору”**. Показать, что богословская полемика и административная практика не одно и то же, но они взаимодействовали: миссионерский язык помогал формировать категорию “опасного сектантства”, а государство переводило её в контроль.

### `7. Короткое окно 1905–1929`

Вставить блок: **“Свобода после 1905 года: легализация без культурного признания”**. 1905 год даёт возможность выхода в публичность, но православная полемика и общественное подозрение продолжаются.

### `12. После ночи`

Вставить блок: **“Диалог без слияния”**. 2012/2024 встречи РПЦ–РС ЕХБ описывать как ограниченный общественный диалог, не как богословское сближение.


---

## V33 update — вставка советского блока по главам

### Глава 9. ВСЕХБ 1944 · 1944–1959

Нужно избегать двух ошибок:

1. писать только “власть создала управляемый союз”;
2. писать только “братья чудесно объединились”.

Правильная сцена: война, разрешённая религиозная жизнь, желание единства, государственная модель контроля, `Братский вестник` как разрешённый голос и поле реальной духовной жизни.

### Глава 10. Инициативная группа · 1959–1965

Построить как драму церковного управления:

- кто имеет право определять жизнь поместной церкви;
- может ли союз принимать документы под давлением государства;
- где граница между компромиссом ради выживания и отступлением от совести;
- как язык “раскола” отличается у ВСЕХБ, СЦ ЕХБ, государства, православных справочников и современных академиков.

### Глава 11. Подпольная печать · 1963–1991

Не делать из самиздата только “героическую типографию”. Показать:

- печать как альтернативная церковная публичность;
- семьи узников как отдельный субъект;
- дети/воспитание/воскресные школы как центральный нерв конфликта;
- Keston/Baylor как внешний канал сохранения и распространения.

### Глава 12. После ночи

Сложность: память о 1960-х до сих пор разделяет нарративы. Нужно честно показать, что постсоветская свобода не автоматически сняла вопрос: кто сохранил верность, кто вынужден был выживать, как говорить о компромиссе без клеветы и героизации.


## V33: куда вставлять lived religion

### Глава 5: Библия, песнь и печать

Добавить отдельную подглаву: `Песни как богословие народа`. Здесь связать Проханова, сборники, перевод/сочинение гимнов, печать и формирование русскоязычного евангельского языка.

### Глава 8: Советская ночь

Добавить карточку: `Как вера выживала дома`: дети, семья, домашнее наставление, запрет/давление на религиозное воспитание, риск для родителей и детей.

### Глава 11: Подпольная печать

Добавить карточку: `Рукописный песенник как архив совести`: песня, память, подполье, хор, собрание.

### Глава 12: После ночи

Добавить блок: `От подпольной семьи к публичной социальной концепции`: РС ЕХБ, свобода совести, социальное служение, межконфессиональное сотрудничество, но без иллюзии полной общественной свободы и без рекламного тона.


---

## V33 addendum — вставка биографических ветвей по главам

### Пролог: До Куры

Вставлять не “предтечи-баптисты”, а людей и семьи, через которых понятна религиозная почва: молоканские семьи, домашнее чтение Писания, духовные христиане, Библейское общество, переселенческие маршруты.

### Ночь на Куре

Главная биографическая сцена: Кальвейты. Не начинать с абстрактной даты 1867, а показать маленькое домашнее собрание: Мартин, Лена, две сестры, Тифлис, молитва, затем рост общины. Это сильнее, чем сухая дата, но требует немецкой проверки.

### Южная штунда

Вставить не только Ратушного/Павлова/Лисицына как “пионеров”, а как людей между деревней, Писанием, православной средой, административным подозрением и новой общиной.

### Петербургская линия

Ветка Пашковых: домашнее собрание, аристократический салон, Александра Ивановна, Пашков, Корф, чтение, пение, благотворительность, напряжение с православной средой.

### Библия, песнь и печать

Проханов как биографический узел: молоканская семья, обращение, крещение, журналы, гимны, молодёжь, социальный проект. Не делать из него безошибочного героя; показать масштаб и спорность.

### Советская ночь / ВСЕХБ 1944

Официальные биографии служителей ВСЕХБ сопоставлять с молчаниями, ограничениями и голосами незарегистрированных.

### Инициативная группа / Подпольная печать

Тут нужны семейные ветви: Хмара, Винсы, Аида Скрипникова, женщины Совета родственников, дети, отобранные или находящиеся под давлением, письма, подпольные журналы.

### После ночи

Показать память: как потомки, общины, архивы, конференции, женское служение, социальное служение и историки собирают распавшиеся свидетельства.


## v36 — Карта вставки биографических ветвей

### Пролог / До Куры

Вставлять не биографии «протобаптистов», а семейно-религиозный фон: молокане, духовные христиане, домашнее чтение Писания, родовые линии, из которых позже некоторые люди пришли к баптизму. Нельзя делать прямую линию «молокане = баптисты».

### Ночь на Куре

Центральная сцена: Кура, Тифлис, Воронин, Кальвейты, Павлов, Иванов-Клышников. Это должна быть глава с сильным визуальным/домашним началом: маленький круг, чтение, вера, крещение, первые путешествия.

### Библия, песнь и печать

Проханов должен идти не только как администратор, а как человек печати, песни, молодёжи и семейного духовного наследия. Вставить связку: молоканский семейный фон → обращение → крещение → журналы → гимны → молодёжь.

### Советская ночь

Не начинать с репрессий. Начать с повседневности: собрание, дети, песенник, дом молитвы, затем показать давление: регистрация, контроль, школа, армия, литература.

### Инициативная группа

Крючков/Винс/Хмара/Храпов — не как иконки, а как разные типы служения: организатор, богословско-церковный протест, мученическая память, тюремная литература.

### Подпольная печать

Совет родственников узников — центральная биографическая ветвь: матери, жёны, семьи, письма, списки, ходатайства, международная огласка. Лидия Винс и Аида Скрипникова должны быть не боковой сноской, а внутренним двигателем главы.

### После ночи

Показать, как биографии становятся памятью: архивы, книги, конференции, сайты, диаспора, восстановление имён, но также риск мифологизации.


---

## v36 — карта биографических ветвей по главам

### Пролог: До Куры

Биографический материал здесь должен быть минимальным. Не создавать ложных предшественников баптизма. Можно дать коллективный портрет: семьи духовных христиан, молокан, читателей Писания, людей, для которых Библия постепенно становилась домашней книгой.

### 1. Ночь на Куре

**Главные BioCase:** Воронин, Кальвейты, Павлов, Иванов-Клышников.  
**Сцена:** маленький домашний круг, чтение Писания, сознательное крещение, первые связи.  
**Риск:** юбилейная ретроспектива превращает сложный процесс в простую легенду основания.

### 2. Южная штунда

**Главные BioCase:** Ратушный, Рябошапка, Лисицын, Онищенко, крестьянские семьи.  
**Сцена:** полевая работа, немецкие колонии, чтение Евангелия, крещение в поле/реке, соседство и конфликт.  
**Риск:** либо стереть немецкое влияние, либо свести всё к немецкому импорту.

### 3. Петербургская линия

**Главные BioCase:** Пашков, Корф, Ливен, женщины-хозяйки собраний, Каргель, Проханов.  
**Сцена:** дом, гостиная, благотворительность, женское удержание собраний после давления.  
**Риск:** салонная романтизация.

### 5. Библия, песнь и печать

**Главные BioCase:** Проханов, гимнографы, редакторы, молодёжь, хоры, рукописные песенники.  
**Сцена:** песня как память, журнал как сеть, молодёжный съезд как лицо будущего.  
**Риск:** сделать песню декоративной, хотя она была духовной инфраструктурой.

### 8–11. Советская ночь / ВСЕХБ / Инициативники / Подпольная печать

**Главные BioCase:** Георгий Винс, Лидия Винс, Аида Скрипникова, Николай Хмара, Николай Храпов, семьи узников, дети.  
**Сцена:** суд, письмо, бюллетень, ребёнок в школе, мать в ходатайстве, хоры под запретом, песня в камере.  
**Риск:** эмоциональная легендаризация. Нужна максимальная документальная дисциплина.

### 12. После ночи

**Главные BioCase:** эмиграция Винсов, архивная память, возвращение дел, музеи, постсоветские свидетельства, социальная концепция, семьи памяти.  
**Сцена:** архив открывается, потомки получают дела, церковь учится говорить о травме без мифа.  
**Риск:** современная конфессиональная память может сглаживать сложность и внутренние конфликты.


---

## v36 — Биографические вставки по главам: уточнённая карта

### Пролог: До Куры

- Не вставлять «биографии протобаптистов». Можно только показать типы религиозной памяти: молоканская семья, духовное чтение, домашняя книжность, но не делать прямую генеалогию.

### 1. Ночь на Куре

- Воронин как событие крещения.
- Кальвейты как семейно-домашная среда.
- Жёны/дети/домашние собрания как сцена, где новое исповедание становится не идеей, а жизнью.

### 2. Южная штунда

- Ратушный, Рябошапка, Основа.
- Семья и деревня: как вера входит в крестьянский дом, меняет воскресенье, чтение, трезвость, отношение к православному приходу.

### 3. Петербургская линия

- Пашков, но не один.
- Ливен, Гагарина, Черткова, Пейкер как женская аристократическая ветвь: домашние собрания, милосердие, больницы, тюрьмы, печать, дети.

### 5. Библия, песнь и печать

- Проханов как редактор и гимнограф.
- Пейкер / `Русский рабочий` как женская печатная линия.
- Молодёжные съезды и `Молодой виноградник`.

### 6. Гонения и совесть

- Павлов как биографический мост: миссионерство, тюрьмы, ссылки, семья.
- Административные документы не должны вытеснять личную цену.

### 8–11. Советская ночь / ВСЕХБ / Инициативная группа / Подпольная печать

- Винсы как семейная сага: Пётр, Лидия, Георгий, дети, эмиграция, зарубежное представительство.
- Совет родственников узников как женско-семейная структура.
- Аида Скрипникова как молодежная/поэтическая/самиздатная ветвь.
- Хмара как martyr-memory, но только с осторожной проверкой деталей.
- Дети верующих как центральное поле конфликта государства и семьи.


## V39 insertion map — где ставить малые биографические истории

### Вставки по главам

**Глава 1. Ночь на Куре**
- Воронин как публичное крещение.
- Кальвейты как домашний круг.
- Тифлисская маленькая община как сцена рождения.

**Глава 2. Южная штунда**
- Ратушный и Основа: крестьянская библейская община.
- Павлов / Иванов-Клышников: поездка, крещение, проповедь, ссылка.

**Глава 3. Петербургская линия**
- Пашковский дом.
- Ливен / Черткова / Гагарина / Пейкер: женская аристократическая и благотворительная ветвь.

**Глава 5. Библия, песнь и печать**
- Проханов: не только лидер, а редактор, гимнограф, молодёжный организатор.
- Молодёжные кружки и съезды как будущий визуальный блок.

**Глава 9–11. ВСЕХБ, Инициативная группа, Подпольная печать**
- Крючков / Винс как leaders, но рядом — Нина, Лидия, семьи, дети.
- Лидия Говорун как детская и родительская тема.
- Лидия Винс как мать, узница, представительница семей.
- Ульяна Германюк как жена узника и самостоятельная ходатайница.
- Аида Скрипникова как молодёжное свидетельство.
- Хмара как martyr-memory case с повышенной проверкой.

**Глава 12. После ночи**
- дети узников как носители памяти;
- интервью и воспоминания — только с маркировкой жанра;
- современное переосмысление через музеи/архивы/передвижные экспозиции.

---

# V39 no-loss expansion — режим «ничего не урезать»

Этот раздел добавлен после замечания: **при консолидации нельзя терять факты, выводы, абзацы, оговорки и рабочие решения из предыдущих проходов**. Поэтому v39 — не краткая выжимка и не рекламный summary, а рабочий master-пакет: в нём должны сохраняться все проверенные линии исследования, но без расползания на сотни файлов.

Правило v39:

1. **Старые v1–v26 и round-файлы не импортируются в репозиторий как рабочая структура**, но считаются черновым архивом исследования, из которого нельзя выбрасывать подтверждённые выводы.
2. **Каждый факт переносится в один из 10 master-файлов**, а не в новый одноразовый файл.
3. **Ни один вывод не должен исчезать при укрупнении**: если вывод ещё не готов для статьи, он переносится в статус `LEAD`, `QUESTION`, `BIOCASE-D`, `MEDIA-GATE`, `ARCHIVE-REQUEST` или `DO-NOT-ASSERT-YET`.
4. **Не сжимать до тезисов там, где нужна аргументация**: важные спорные темы требуют абзацев, контраргументов, источниковой критики и плана проверки.
5. **Не превращать источники в “истину”**: баптистский, православный, советский, зарубежный, светский, архивный и семейно-мемуарный голоса должны быть разведены.


## V39: карта вставки без потери больших абзацев

Серия должна избегать двух ошибок:

1. превращение в энциклопедическую сухую ленту;
2. превращение в набор эмоциональных историй без проверки.

Поэтому каждый BioCase вставляется как короткая, но насыщенная сцена, а не как случайная вставка.

### Пример структуры BioCase-сцены

1. 2–3 предложения исторического контекста.
2. Кто человек/семья и почему важны.
3. Что говорит основной источник.
4. Какие есть риски/другие голоса.
5. Один проверочный вопрос.
6. Возврат к главному аргументу главы.

### Главы и обязательные биографические вставки

- `Ночь на Куре` — Воронин + Кальвейты.
- `Южная штунда` — Ратушный/Рябошапка/Лисицын.
- `Петербургская линия` — Пашков + Ливен/Черткова/Гагарина/Пейкер.
- `Библия, песнь и печать` — Проханов, гимнография, молодёжь.
- `Гонения и совесть` — Павлов, Иванов-Клышников, ссылки.
- `ВСЕХБ 1944` — официальные лидеры + рядовая община.
- `Инициативная группа` — Крючков, Винс, Скрипникова, Хмара.
- `Подпольная печать` — Совет родственников, женщины, семьи, дети.
- `После ночи` — постсоветские союзы, социальная концепция, диалог с РПЦ, память узников.


---

## V39. No-loss insertion map: куда вставлять человеческие истории

### Пролог: До Куры

Вставлять не биографии баптистов, а “предбиографические условия”: книжники, читатели, переводчики, старообрядческие семьи, молоканские общины, библейское чтение. Но прямо писать: это ещё не баптисты.

### Глава 1. Ночь на Куре

Главные BioCase: Воронин, Кальвейты, Павлов молодой, Иванов-Клышников. Вставка должна быть сценической: река, дом, чтение, разговор о крещении, маленькая община.

### Глава 2. Южная штунда

BioCase: Ратушный, Рябошапка, Основа, немецко-меннонитские контакты, крестьянские семьи. Вставка: деревенское чтение Писания, собрание, ярлык “штунда” извне, самоопределение изнутри.

### Глава 3. Петербургская линия

BioCase: Пашков, Корф, Редсток, Ливен, Черткова, Гагарина, Пейкер, Каргель. Вставка: дом как церковь, дом как миссия, женщины как инфраструктура служения.

### Глава 5. Библия, песнь и печать

BioCase: Проханов, Каргель, молодёжные кружки, `Молодой виноградник`, детские разделы, гимнография. Вставка: песня как богословие общины.

### Глава 8–9. Советская ночь и ВСЕХБ

BioCase: служители официального ВСЕХБ, редакторы `Братского вестника`, местные пасторы, семьи, которые жили между регистрацией и совестью.

### Глава 10–11. Инициативная группа и подпольная печать

BioCase: Крючков, Винс, Лидия Винс, Совет родственников, Аида Скрипникова, Ульяна Германюк, Зинаида Вильчинская, Анна Козорезова, дети верующих, Хмара, Храпов.

Эти главы должны быть самыми человеческими: письма, суды, дети, списки узников, перепечатка, тайники, машинки, семейная помощь, международная огласка.

### Глава 12. После ночи

BioCase: Каретникова, память, конференции, возвращение истории, постсоветский диалог, новые союзы, архивирование, спор памяти. Здесь важно показать не только свободу после 1991 года, но и борьбу за интерпретацию прошлого.



---

## V52 addition — `Христианин` 1906 №5–6 moved from issue-level to story-card/register layer

V52 не просто добавляет ещё один журнал, а углубляет уже открытый корпус №5–6 до writing-ready уровня:

- `19-khristianin-1906-05-06-live-cards-v52.md` — живые карточки: песня, маловерие, горшечник, второй Адам, дети, плен греха, Кавказский столяр, Христова свобода, Дух Святой, небесное сокровище, Канадский пожар, телеграф, царедворец.
- `20-khristianin-1906-05-06-register-v52.md` — быстрый регистр людей, мест, предметов и narrative openings.
- `21-next-corpus-corridor-utrennyaya-zvezda-baptist-v52.md` — следующая очередь: не хаотично, а через public-square dossier `Утренней звезды` и зрелый `Баптист` 1909–1911.

Итоговый статус: `Христианин` 1906 №5–6 теперь можно использовать не только как богословский источник, но и как материал для живой исторической прозы. Открытый gap: полный extraction разделов `На ниве Божией` и `Христианин` 1906 №3.


# V52 insertion block — `Утренняя звезда` 1910

## `peterburgskaya-liniya`

Use `Утренняя звезда` №40 as a major narrative scene: rain, boards, chairs, scaffold, 60-person choir, delegates, guests, curious public, workers watching from roof/yard, V. A. Fetler, V. G. Pavlov, Mr. Byford, I. V. Kargel, I. S. Prokhanov. This scene can anchor the transition from private circles and print culture to visible city presence.

## `goneniya-i-sovest`

Use №5 `Любовь к врагам` as an anti-revenge conscience card. It shows Scripture shaping public ethics: David refuses to kill Saul; Christ prays for enemies; Rom. 12 calls believers not to repay evil with evil.

## `bibliya-pesn-pechat`

Use №7 `Драгоценное правило` as newspaper Bible exposition: the Golden Rule is impossible without new birth. This helps prevent a shallow “social gospel” reading.

## future `evangelie-i-modernost`

Use №19 `Люди-птицы` only after PDF/OCR. Potential topic: aviation as early 20th-century modernity seen through evangelical press.

## future `trezvost-i-narodnaya-bol`

Use №7 coffee-versus-alcohol micro-story and №18 `Зло невоздержания` after PDF/OCR.

## ordinary-believer layer

Use №44 widow/6 rubles/pension story to prevent series from becoming only leader-history.

---

# V52 insertion map — `Утренняя звезда` 1910 late-public layer

## Chapter: `goneniya-i-sovest`

Insert file: `27-utrennyaya-zvezda-1910-43-religious-freedom-dossier-v52.md`.

Placement: after explanation of 1905 legal opening and before vivid persecution anecdotes.

Reason: this dossier gives mechanisms, not just emotions — registration, conversion rules, schools, congresses, meetings, governors, police, cemeteries.

Ready subheading:

> Свобода, которую ещё нужно было доказывать: 1905–1910

## Chapter: `ordinary-believers` / `women-and-family` / `poverty`

Insert file: `28-utrennyaya-zvezda-1910-44-widow-prayer-civic-life-dossier-v52.md`.

Placement: after major male leaders and before/inside social life chapter.

Reason: prevents the series from becoming only Prokhanov-Fetler-Pavlov-Kargel. Shows unnamed widow, sickness, coal debt, prayer, petition, presbyter's help.

## Chapter: `trezvost-i-narodnaya-bol`

Insert file: `26-utrennyaya-zvezda-1910-18-19-temperance-aviation-dossier-v52.md` after OCR is completed.

Current use: framework only; do not final-write details until PDF/OCR.

## Chapter: `evangelie-i-modernost`

Use `Люди-птицы` as bridge between technology and the gospel. Current use: target and conceptual scaffold only.

## V52 insertion map — where `Утренняя звезда` now belongs

### Chapter: `Площадь, молитва и печать`

Use files:

- `22-utrennyaya-zvezda-1910-public-square-dossier-v52.md`
- `24-utrennyaya-zvezda-1910-house-of-prayer-scene-v52.md`
- `27-utrennyaya-zvezda-1910-43-religious-freedom-dossier-v52.md`
- `28-utrennyaya-zvezda-1910-44-widow-prayer-civic-life-dossier-v52.md`
- `30-utrennyaya-zvezda-1910-18-19-retrieval-dossier-v52.md`
- `31-utrennyaya-zvezda-1910-newspaper-identity-dossier-v52.md`
- `32-utrennyaya-zvezda-1910-public-square-writing-pack-v52.md`

Narrative order:

1. Why print publicness matters.
2. `Утренняя звезда` asks readers to support it as their own organ.
3. Petersburg house of prayer: visible evangelical presence.
4. Five years of incomplete freedom: law, police, governors, cemeteries.
5. Widow and six rubles: prayer, poverty, presbyter, treasury.
6. Kabak and airplane: drunkenness and aviation as adjacent windows into Russian society.
7. Conclusion: early evangelicals are a praying and publishing public.

Do **not** insert №18/№19 as fully interpreted article bodies yet. Use them as a marked lead until PDF/OCR is closed.


---

## V60 insertion — future chapter: paper network / corpus statistics

Potential chapter:

> `Бумажная сеть братства: журналы, газеты, книги, письма и самиздат русских баптистов`

Use V60 census files as statistical spine. Do not publish 258 as “all Baptist publications”; publish it as “official RSEHB visible archive snapshot across seven title pages”. Then expand to Rigovanov/Stunda, MBChurch, Toronto, Baylor/Keston, Commons and book/brochure census.


---

## [4] SOURCE: `baptists_v93/37-chapter-draft-public-square-v60.md`

# Chapter draft v52 — `Кабак, аэроплан и Гефсимания`: `Утренняя звезда` 1910 как евангельская газета на городской площади

Дата: 2026-06-23  
Статус: **large chapter draft / writing-ready / needs OCR-marked verification**  
Основание: v47–v50 dossiers + official RSEHB issue list/article records + `Иисус, идущий по морю` full article text on RSEHB + v52 synthesis.

---

## 0. Как пользоваться этим файлом

Это не окончательная опубликованная статья, а **большой рабочий черновик главы**. Его можно отдавать агенту как основу для статьи в серии `Баптисты России`, но с тремя правилами:

1. Всё, где стоит `[quote needed after OCR]`, нельзя превращать в точную цитату.
2. Всё, где стоит `[facsimile needed]`, нельзя закреплять как page/column evidence.
3. Общие выводы можно использовать как интерпретацию только вместе с уже заведёнными source-ledger записями.

---

## 1. Тезис главы

В 1910 году `Утренняя звезда` показывала евангельское движение не только как круг молитвенных собраний и проповедей, но как народ, выходящий в городскую публичность. Газета говорила о трезвости, аэропланах, закладке молитвенного дома, съезде, праве на свободу совести, вдовьей бедности и Христе, Который в Гефсимании выходит навстречу вооружённым людям и говорит: `Это Я`.

Эта пестрота тем не случайна. Именно в ней виден ранний евангельский public-square instinct: верующие не хотели исчезнуть в частной религиозности, но и не хотели строить политическую агрессию. Они учились говорить публично, печатно, по-библейски, с молитвой, совестью и гражданской трезвостью.

---

## 2. Открывающая сцена: город, который надо научиться видеть

Представим Петербург 1910 года. В одном углу города спорят о свободе совести и разрешениях на собрания. В другом — люди смотрят на аэропланы, эти новые машины, заставляющие толпу поднимать глаза к небу. Где-то рядом строится молитвенный дом: дождь, хор, рабочие, служители, гости, слова о Христе как основании. А в бедной комнате верующая вдова думает не о больших съездах, а о шести рублях за уголь.

Евангельская газета связывает все эти сцены одной оптикой. Она спрашивает не только: “Что происходит в России?” Она спрашивает: “Как на это смотрит человек, который верит Писанию, молится Христу и хочет жить с чистой совестью?”

Так `Утренняя звезда` становится не просто архивным изданием, а картой раннего евангельского взгляда на общество.

---

## 3. Почему это не просто “баптистский журнал”

Для серии важно не смешивать все издания в одну кучу.

- `Баптист` 1907 даёт церковно-исповедальный каркас: Писание, Бог, грех, искупление, церковь, крещение, вечеря, порядок.
- `Христианин` 1906 даёт петербургско-евангельскую ткань сердца, семьи, детей, песни, миссии, Сперджена, живых историй.
- `Утренняя звезда` 1910 даёт public-square регистр: газета, город, съезд, закон, бедность, трезвость, прогресс, молитвенный дом.

Поэтому `Утреннюю звезду` лучше не подавать как “ещё один журнал о баптистах”. Правильнее: это печатный публичный голос евангельского движения, связанный с прохановской линией, но полезный для всей истории русских баптистов и евангельских христиан.

---

## 4. Газета как орган движения

Внутренний журнал назидает уже собранных. Газета же делает ещё одно дело: она собирает разрозненных читателей в воображаемое братство. Человек в провинции, получая номер, видел, что где-то строится молитвенный дом, где-то готовится съезд, где-то обсуждают свободу совести, где-то борются с пьянством, где-то рассказывают о бедной вдове, а где-то публикуют евангельское размышление о Христе.

Так печать создавала не только информацию, но и принадлежность.

В v49 уже заведён отдельный newspaper-identity dossier: по PDF-snippets разных номеров видно повторяющееся обращение поддерживать `Утреннюю звезду`, признавать её своим органом, рекомендовать другим и оказывать нравственную поддержку. Но этот узел всё ещё требует факсимильной проверки: `[facsimile needed: exact wording/page/column for reader-support appeals]`.

**Draft paragraph for article:**

> `Утренняя звезда` хотела быть не складом религиозных заметок, а органом движения. Её читатель не просто получал тексты; он вовлекался в общий голос. Газета связывала столицу и провинцию, проповедь и право, дом молитвы и бедную комнату, съезд и молитву. Так печатное слово превращалось в пространство братского сознания.

---

## 5. Закладка молитвенного дома: вера становится видимой

Сцена из №40 — одна из самых сильных для визуальной и повествовательной части серии. Здесь вера перестаёт быть абстрактной.

Опорные элементы из v47/v48:

- Петербург;
- закладка молитвенного дома;
- дождь;
- хор;
- рабочие;
- служители и гости;
- Христос как основание;
- любовь как “цемент” единства;
- молитвенный дом как видимое присутствие евангельского народа в городе.

Это не надо писать как “триумфальное строительство баптистской крепости”. Правильнее: община получает тело в городе. У неё появляется место, куда можно прийти, где можно петь, молиться, проповедовать, принимать гостей, собирать съезды, быть видимой и узнаваемой.

**Draft paragraph:**

> Закладка молитвенного дома превращает евангельскую историю в городскую сцену. Дождь, доски, хор, рабочие, проповедники и гости создают почти кинематографический кадр: вера не прячется, но и не навязывает себя мечом. Она строит место молитвы. Для ранних евангельских христиан молитвенный дом был не просто удобной крышей над собранием. Он был видимым знаком: в этом городе есть народ, который хочет жить перед Богом открыто, трезво и мирно.

**Where to insert:** после главы о петербургской линии и перед блоком о свободе совести.

---

## 6. Съезд: братство учится говорить вместе

`К съезду баптистов` — важный мост между газетой и организацией. Article-record РС ЕХБ даёт `Утренняя звезда` 1910 №34, а другая годовая выдача местами даёт №35. Поэтому в v50 это зафиксировано как discrepancy, а не как решённый вопрос.

Содержательно статья важна уже по verified lead:

- всероссийский съезд евангельских христиан-баптистов;
- Петербург;
- даты 1–10 сентября 1910;
- газета как механизм подготовки, приглашения, согласования ожиданий;
- public voice перед большим братским событием.

**Draft paragraph:**

> Газета не только описывала жизнь движения, но и помогала ему собираться. Статья `К съезду баптистов` показывает Петербург как место, где разрозненные общины должны услышать друг друга и научиться говорить вместе. Это не стоит описывать сухим словом “централизация”. Ранний съезд — это ещё и духовная география: люди приезжают из разных мест, чтобы увидеть, что их вера не одинока, что у неё есть общая речь, общие вопросы и общая ответственность.

**Verification note:** `[facsimile needed: №34/№35, page/column, exact opening and date line]`.

---

## 7. Свобода совести: манифест есть, но жизни ещё нет

Статья `Пятилетие свободы (17 Окт. 1905 — 17 Окт. 1910)` из №43 — один из самых важных public-square узлов. Она не даёт наивного восторга и не превращается в революционный памфлет. Смысл тоньше: свобода провозглашена, но в быту ещё ограничена.

Опорные темы из v48:

- регистрация общин;
- переход из православия;
- вероисповедные школы;
- съезды и собрания;
- губернаторы и полиция;
- кладбища и похороны;
- местные препятствия.

**Draft paragraph:**

> Через пять лет после 1905 года `Утренняя звезда` смотрит на свободу совести без иллюзий. Законодательные двери приоткрылись, но за ними оставались губернаторы, полиция, местные запреты, кладбищенские конфликты, трудности регистрации и подозрительность к тем, кто выходил из православной среды. Эта статья важна тем, что евангельская печать говорит не языком мести, а языком гражданской диагностики: свобода уже названа, но ещё не стала нормальной жизнью.

**Why this matters for Baptist/Russian evangelical series:**

История баптистов в России — это не только “их гнали” и не только “они спорили о крещении”. Это ещё история людей, которые добивались нормального гражданского существования: права собираться, молиться, хоронить своих, воспитывать детей, иметь школы, съезды и общины без постоянной административной угрозы.

---

## 8. Вдова и шесть рублей: бедность как богословский документ

История из №44 — один из самых сильных живых эпизодов всей подборки. Она маломасштабная, но именно поэтому мощная.

Опорные элементы:

- верующая вдова;
- болезнь;
- долг за уголь;
- 6 рублей;
- просьба к пресвитеру написать прошение правительству;
- молитва во имя Христа;
- ответ через губернское казначейство;
- пожизненная пенсия 6 рублей в месяц;
- благодарственная молитва.

**Draft paragraph:**

> После больших разговоров о свободе совести газета вдруг приводит историю о вдове и шести рублях. Это не случайное сентиментальное украшение. Перед нами маленький богословский документ: бедная женщина верит, что Христос слышит молитву, но её вера не отменяет письма в государственное учреждение. Пресвитер пишет прошение, казначейство отвечает, назначается пенсия. Молитва и гражданский порядок не сталкиваются, а оказываются в одной истории. Евангельская вера здесь не уходит от быта; она входит в комнату, где холодно, где нужен уголь, где шесть рублей решают вопрос жизни.

**Warning:** не превращать в prosperity story. Это не “молитва всегда даёт деньги”, а свидетельство о доверии Богу в бедности и о гражданском действии без потери молитвенной зависимости.

---

## 9. Кабак и аэроплан: две силы, тянущие человека вниз и вверх

№18 и №19 пока требуют полного OCR, но уже как editorial-neighbour pair они дают почти готовую сцену.

- №18: `Зло невоздержания`, пьянство, библейский диагностический вход `У кого вой?...`.
- №19: `Люди-птицы`, Петербург, неделя полётов с 26 апреля по 2 мая 1910, аэропланы, Коломяжский ипподром.

**Interpretive frame:**

Кабак и аэроплан — не просто контраст старого и нового. Это два образа человека. Один образ — человек, которого грех тянет вниз, разрушает волю, дом, трезвость, труд. Другой — человек, который научился подниматься в воздух силой техники. Но газета, вероятно, не поклоняется ни одному полюсу. Она видит человеческую рану и человеческое изобретение, но главный вопрос остаётся духовным: что происходит с сердцем?

**Draft paragraph:**

> В соседстве статей о невоздержании и о “людях-птицах” открывается почти символическая Россия 1910 года. С одной стороны — пьянство, старая народная рана, тянущая человека вниз. С другой — аэроплан, новое чудо техники, заставляющее толпу смотреть вверх. Евангельская газета оказывается между кабаком и небом, между падением и полётом. Но её главный вопрос не технический и не моралистический: может ли человек, научившийся летать, быть освобождён от того, что разрушает его сердце?

**Strict limitation:** до OCR нельзя описывать авторскую оценку аэропланов как “восторг”, “ирония”, “осуждение” или “апологетика прогресса”. Можно говорить только: статья существует; она связана с прогрессом/птицами; lead фиксирует полёты в Петербурге, даты и Коломяжский ипподром.

---

## 10. “Иисус, идущий по морю”: мост к мотиву `Это Я`

В v52 стоит добавить в public-square chapter не только №47 `Это Я`, но и №28 `Иисус, идущий по морю`, потому что РС ЕХБ даёт полный текст этой статьи. Она помогает увидеть, что формула `это Я, не бойтесь` у `Утренней звезды` не случайный поздний лозунг, а устойчивый евангельский мотив утешения среди страха.

Главные темы статьи №28:

- ученики понуждены Христом войти в лодку;
- Христос молится, пока лодку бьют волны;
- ученики пугаются, потому что не узнают Его;
- Христос говорит: `это Я, не бойтесь`;
- Пётр начинает тонуть, когда смотрит на ветер;
- урок: взирать на Христа, а не на бушующую воду.

**Draft paragraph:**

> Мотив `это Я, не бойтесь` появляется в `Утренней звезде` не как украшение, а как пастырский нерв. В статье о Христе, идущем по морю, страх учеников становится образом верующего человека среди бури. Лодку бьют волны, Христос молится, ученики принимают Его за призрак, а затем слышат голос, который возвращает им реальность: это не призрак, это Господь. Для газеты, которая пишет о свободе, бедности, городских тревогах и общественных вопросах, такой текст важен: публичная христианская жизнь держится не на смелости характера, а на слышании голоса Христа.

**Connection to №47:**

В №28 Христос говорит “это Я” ученикам среди бури. В №47 Христос говорит “это Я” уже не испуганным ученикам, а людям, пришедшим с оружием в Гефсиманию. Один текст утешает верующих среди волн; другой показывает Христа перед насилием.

---

## 11. Гефсимания: публичность без мести

№47 `Это Я` должен стать богословским центром главы, но full OCR пока всё ещё нужен. Article-record фиксирует:

- `Утренняя звезда` 1910 №47;
- Ин. 18:1–11;
- Гефсимания;
- Христос выходит за поток Кедрон;
- мотив `Это Я`.

Даже на уровне verified lead видно, почему этот текст важен: после всех общественных сюжетов — свобода, съезд, бедность, город, прогресс — газета возвращает читателя к Христу, Который не прячется и не мстит.

**Draft paragraph:**

> В конце public-square дуги стоит Гефсимания. Это важно. Евангельская печать могла говорить о правах, законах, губернаторах, полиции, съездах и общественных ранах, но её центр не в обиде и не в силовом ответе. Христос выходит навстречу тем, кто пришёл с оружием, и говорит: `Это Я`. В этой сцене евангельская публичность получает форму: открытость без мстительности, твёрдость без насилия, исповедание без меча.

**Strict limitation:** не описывать подробно развитие статьи №47 без OCR; использовать только lead + богословскую связь с Ин. 18:1–11.

---

## 12. Скелет будущей статьи для сайта

### Title option A
**Кабак, аэроплан и Гефсимания: как `Утренняя звезда` вывела русское евангельское движение на площадь**

### Title option B
**Газета на площади: `Утренняя звезда` 1910 года и публичный голос русских евангельских христиан**

### Title option C
**Молитвенный дом, вдова и люди-птицы: public-square мир `Утренней звезды`**

---

### Suggested article structure

1. **Вступление:** Петербург 1910 года: город, газета, вера, публичность.
2. **Не просто журнал:** чем `Утренняя звезда` отличается от `Баптиста` и `Христианина`.
3. **Орган движения:** газета собирает читателей, просит поддержки, формирует общий голос.
4. **Дом молитвы:** вера получает видимое место в городе.
5. **Съезд:** общины учатся говорить вместе.
6. **Свобода совести:** провозглашена, но не стала обычной жизнью.
7. **Вдова и 6 рублей:** молитва, бедность и гражданский порядок.
8. **Кабак и аэроплан:** грех тянет вниз, техника поднимает вверх, но сердце остаётся главным вопросом.
9. **`Это Я`:** Христос среди бури и в Гефсимании.
10. **Вывод:** ранние евангельские христиане были не антиобщественными мистиками и не революционными активистами, а молящимся, печатающим, собирающимся народом с публичной совестью.

---

## 13. Почти готовый full draft 1.0

Ниже — связный черновик, который можно использовать как основу статьи после fact/OCR pass.

### Кабак, аэроплан и Гефсимания

В 1910 году русская евангельская газета могла говорить о вещах, которые на первый взгляд плохо соединяются друг с другом: о пьянстве и аэропланах, о молитвенном доме и съезде, о губернаторах и кладбищах, о вдове и шести рублях, о Христе среди бури и Христе в Гефсимании. Но именно эта пестрота делает `Утреннюю звезду` одним из самых важных источников для истории русских баптистов и евангельских христиан.

Перед нами не просто религиозный листок с назидательными текстами. Это газета движения, которое училось жить публично. Оно уже имело проповеди, собрания, песни, споры о крещении и вероучительные тексты. Но ему нужно было ещё научиться говорить с городом, законом, бедностью, прогрессом, государством и собственной рассеянной аудиторией.

`Баптист` давал исповедальный позвоночник. Там говорили о Писании, Боге, грехе, искуплении, крещении, церкви и порядке. `Христианин` раскрывал евангельскую ткань сердца: Христос распятый, свобода от греха, дети, молодёжь, песни, семейное благочестие, живые истории и миссия. А `Утренняя звезда` выводила эту веру на площадь. Она ставила рядом молитвенный дом и общественный закон, вдовий уголь и съезд, кабак и аэроплан.

Одним из самых зримых символов этой публичности стала сцена закладки молитвенного дома. В ней вера получила место в городе. Это уже не только домашнее собрание, не только спор с миссионерским журналом и не только внутреннее назидание для своих. Дождь, хор, рабочие, служители, доски, гости — всё это превращало евангельское движение в видимую городскую реальность. Молитвенный дом был не просто зданием. Он говорил: здесь есть народ, который молится, поёт, строит и хочет жить открыто.

Но видимость требовала не только стен. Она требовала голоса. Поэтому газета была не приложением к движению, а частью самого движения. Она связывала столицу и провинцию, служителей и простых читателей, богословие и городскую повседневность. Через неё читатель узнавал, что он не один. Где-то готовится съезд. Где-то строится дом молитвы. Где-то обсуждают свободу совести. Где-то бедная вдова молится о шести рублях. Где-то люди смотрят на аэропланы. А в центре всего этого звучит Евангелие.

Статья `К съезду баптистов` показывает, как печать помогала братству собираться. Съезд был не просто административным мероприятием. Это была школа общего голоса. Разные общины должны были увидеть друг друга, услышать друг друга и понять, что их вера имеет не только местную, но и всероссийскую ответственность. Поэтому Петербург в этой истории становится не только столицей империи, но и местом, где евангельское движение пытается обрести общую речь.

Рядом с этим стоит тема свободы совести. Через пять лет после 1905 года газета не торжествует наивно. Она видит, что свобода провозглашена, но ещё не стала обычной жизнью. Общины трудно регистрировать. Собрания зависят от местной власти. Переход из православия вызывает административные препятствия. Вопросы школ, кладбищ, похорон, съездов и полиции остаются болезненными. Это не язык подпольной ярости, но и не язык декоративной благодарности. Это гражданский диагноз: свобода названа, но ей ещё надо войти в повседневность.

А затем газета резко меняет масштаб и рассказывает о вдове. Ей нужны шесть рублей за уголь. Она больна. Она не может заработать. Она просит пресвитера написать прошение правительству и при этом молится во имя Христа. В этой маленькой истории сходятся молитва, бедность, государственное учреждение и церковное служение. Это не сентиментальная вставка. Это богословие в комнате, где холодно. Евангельская вера здесь не убегает от быта; она входит в долг за уголь и в прошение к казначейству.

Особенно выразительно рядом стоят темы кабака и аэроплана. В одном номере газета говорит о зле невоздержания, вводя тему пьянства через библейский язык. В следующем — пишет о людях, которые летали на аэропланах в Петербурге. Перед нами два образа человека: один падает вниз под властью греха, другой поднимается вверх силой техники. Россия 1910 года оказывается между кабаком и небом. Но евангельская газета не поклоняется технике и не ограничивается морализмом. Она задаёт более глубокий вопрос: что происходит с сердцем человека?

Именно поэтому public-square дуга не может закончиться ни законом, ни техникой, ни бедностью, ни съездом. Она должна вернуться ко Христу. В статье о Христе, идущем по морю, ученики пугаются среди бури и принимают Его за призрак, но слышат: `это Я, не бойтесь`. Этот мотив затем особенно важен рядом с Гефсиманией. Там Христос выходит уже не к испуганным ученикам среди волн, а к людям, пришедшим с оружием. И снова центр не в человеческой силе, а в Нём Самом.

Так `Утренняя звезда` учит публичной вере без мести. Евангельские христиане могли говорить о свободе совести, просить права, собирать съезды, строить молитвенные дома, бороться с пьянством, замечать прогресс, помогать бедным и писать газету. Но их публичность не должна была становиться насилием. В центре стоял Христос, Который не прячется, не мстит и не строит Своё царство мечом.

Поэтому `Утренняя звезда` — один из ключевых источников для понимания русских баптистов и евангельских христиан. Она показывает не только, во что они верили, но как они учились быть видимыми: молиться, печатать, строить, просить, спорить, собираться и говорить о России перед лицом Христа.

---

## 14. Что ещё нужно перед публикацией

### Mandatory OCR/facsimile checks

1. №18 `Зло невоздержания` — page/column OCR, полный ход аргумента.
2. №19 `Люди-птицы` — page/column OCR, тон автора, описание Коломяжского ипподрома.
3. №34/35 `К съезду баптистов` — решить номер, page/column.
4. №47 `Это Я` — полный OCR, нельзя строить детальную экзегезу только по lead.
5. Reader-support appeals — exact wording “свой орган” etc.

### Optional but high-value checks

1. №28 `Иисус, идущий по морю` — сверить web-reprint с PDF №28.
2. №40 молитвенный дом — page/column + возможный visual caption.
3. №41 первая полоса — media rights/caption/crop.
4. №48 year-end issue — проверить, есть ли итоговый editorial.

---

## 15. Варианты лид-абзацев для сайта

### More literary

В Петербурге 1910 года евангельская газета смотрела сразу в разные стороны: на строящийся молитвенный дом, на бедную вдову, на полицейские ограничения, на съезд, на кабак и на аэропланы. Но её взгляд не рассыпался. Всё это она читала перед лицом Христа.

### More historical

`Утренняя звезда` 1910 года важна потому, что показывает раннее евангельское движение в публичном пространстве Российской империи. Это не только вероучение и не только внутренняя церковная жизнь, а печатная попытка говорить о городе, законе, бедности, прогрессе и свободе совести.

### More theological

Евангельская публичность `Утренней звезды` начинается не с политики, а с Христа. Поэтому газета могла говорить о праве, бедности, пьянстве и технике, не теряя центра: человек нуждается не только в свободе собраний и не только в техническом прогрессе, а в Господе, Который говорит среди страха: `Это Я`.


---

## [5] SOURCE: `baptists_v93/111-zip-and-repo-audit-v85.md`

# v85 — ZIP + repository cross-check audit

Date: 2026-06-25.

Scope: structural audit of the current research ZIP and public GitHub repository `FedorMilovanov/gb-is-my-strength`, with a periodical-corpus emphasis. This file does **not** claim that every PDF/DJVU has been downloaded or OCR-verified. It records what can be safely concluded from the v84 ZIP structure, the repo tree, and the fresh web crawl.

## 1. ZIP structure check

The v84 base pack contains **149 files** before v85 additions: **118 `.md`**, **25 `.csv`**, **8 `.txt`**, total payload about **2.38 MB**. This is a research-control pack, not a media archive: it mainly contains ledgers, protocols, dossiers, crawl plans, and synthesis notes.

Largest files in v84 are still the persecution/samizdat dossiers and the big source ledgers, not the new periodical crawl notes. That means the pack is weighted toward narrative/source synthesis, while the new periodical work still needs issue-level census and download/OCR status.

## 2. Term coverage inside ZIP

| Term | Hits | Files | Example files |
|---|---:|---:|---|
| Баптист Украины | 44 | 22 | 05-periodicals-print-corpus-master.md; 10-agent-workflow-next-search-master.md; 100-agent-crawl-prompts-v82.md; 102-small-periodicals-and-prokhanov-network-v83.md; 104-bratskiy-vestnik-mbchurch-official-corpus-v83.md; 105-v83-priority-conclusion.md |
| Вестник Спасения | 135 | 47 | 01-series-book-master-architecture.md; 02-source-critical-protocol-master.md; 05-periodicals-print-corpus-master.md; 08-chronology-data-model-master.md; 09-chapter-insertion-map-master.md; 10-agent-workflow-next-search-master.md |
| Вестник Истины | 125 | 46 | 01-series-book-master-architecture.md; 02-source-critical-protocol-master.md; 05-periodicals-print-corpus-master.md; 07-media-photo-permissions-master.md; 09-chapter-insertion-map-master.md; 10-agent-workflow-next-search-master.md |
| Бюллетень | 214 | 43 | 01-series-book-master-architecture.md; 02-source-critical-protocol-master.md; 05-periodicals-print-corpus-master.md; 07-media-photo-permissions-master.md; 09-chapter-insertion-map-master.md; 10-agent-workflow-next-search-master.md |
| Братский листок | 68 | 35 | 05-periodicals-print-corpus-master.md; 07-media-photo-permissions-master.md; 10-agent-workflow-next-search-master.md; 102-small-periodicals-and-prokhanov-network-v83.md; 105-v83-priority-conclusion.md; 106-agent-crawl-prompts-v83.md |
| Утренняя звезда | 636 | 72 | 02-source-critical-protocol-master.md; 05-periodicals-print-corpus-master.md; 07-media-photo-permissions-master.md; 08-chronology-data-model-master.md; 09-chapter-insertion-map-master.md; 10-agent-workflow-next-search-master.md |
| Христианин | 559 | 75 | 02-source-critical-protocol-master.md; 05-periodicals-print-corpus-master.md; 06-foreign-archives-secular-media-master.md; 07-media-photo-permissions-master.md; 08-chronology-data-model-master.md; 09-chapter-insertion-map-master.md |
| Братский вестник | 587 | 61 | 02-source-critical-protocol-master.md; 05-periodicals-print-corpus-master.md; 06-foreign-archives-secular-media-master.md; 09-chapter-insertion-map-master.md; 10-agent-workflow-next-search-master.md; 100-agent-crawl-prompts-v82.md |
| Русский рабочий | 11 | 10 | 05-periodicals-print-corpus-master.md; 09-chapter-insertion-map-master.md; 10-agent-workflow-next-search-master.md; 102-small-periodicals-and-prokhanov-network-v83.md; 104-bratskiy-vestnik-mbchurch-official-corpus-v83.md; 106-agent-crawl-prompts-v83.md |
| Слово истины | 29 | 18 | 05-periodicals-print-corpus-master.md; 07-media-photo-permissions-master.md; 10-agent-workflow-next-search-master.md; 100-agent-crawl-prompts-v82.md; 104-bratskiy-vestnik-mbchurch-official-corpus-v83.md; 107-periodical-web-crawl-v84-verified-leads.md |
| Призыв | 22 | 16 | 107-periodical-web-crawl-v84-verified-leads.md; 108-lost-and-sparse-periodicals-v84.md; 11-periodical-gold-extraction-v60.md; 12-baptist-1907-doctrine-dossier-v60.md; 16-khristianin-1906-next-issues-map-v60.md; 17-khristianin-1906-05-freedom-captivity-dossier-v60.md |

Interpretation: `Братский вестник`, `Христианин`, and `Утренняя звезда` are heavily represented; `Баптист Украины`, `Призыв`, and sparse titles are present but still thin. This supports a v85/v86 shift from essays to row-level registers.

## 3. Repository structure check

Public GitHub tree shows `baptisty-rossii/` as a real series area with section folders: `dva-sezda-1884`, `goneniya-i-sovest`, `iniciativnaya-gruppa`, `noch-na-kure`, `peterburgskaya-liniya`, `podpolnaya-pechat`, `research`, `sovetskaya-noch`, `spravochnik`, `vsehib-1944`, `yuzhnaya-shtunda`, plus `index.html`.

The repo `baptisty-rossii/research` folder already contains a large research chain, including files numbered into the 70s and specialist files on public perception, anti-sect rhetoric, theological identity, and source ledgers. Therefore the ZIP should **not** be merged blindly. It needs a curated bridge file, otherwise the repo will become harder to navigate.

## 4. High-value integration conclusion

The next repo-side integration should be:

1. Add one compact `periodicals-corpus-master-ledger.md` under `baptisty-rossii/research/`, not dozens of new files.
2. Add CSV registers under `baptisty-rossii/research/raw-sources/periodicals/` or similar.
3. Link the periodical ledger from `podpolnaya-pechat` and `vsehib-1944`, because the periodicals support both official and underground lines.
4. Keep ZIP as working archive; repo gets polished, stable outputs.

## 5. Verification level

Current status after v85:

- `catalog_seen`: strong for major corpora.
- `link_visible`: strong for `Баптистъ`, official RSEHB fragments, Toronto Samizdat rows.
- `download_ok`: **not closed** in this session.
- `page_counted`: only where catalog pages explicitly provide page counts, especially Toronto/Baylor examples.
- `ocr_ready`: **not closed** in this session.


---

## [6] SOURCE: `baptists_v93/115-repo-integration-map-v85.md`

# v85 — repository integration map for `gb-is-my-strength`

Date: 2026-06-25.

## What the public repo already has

The public repository has a real `baptisty-rossii` series shell with folders for origins, Soviet night, official ВСЕХБ, initiative group, underground press, persecution/conscience, Petersburg line, and reference material. The `research` folder is already large and includes numbered source packs up to at least the 70s.

## What the ZIP adds that the repo does not yet express cleanly

The ZIP v84/v85 adds a specialist periodical-corpus track:

- visible issue gaps between RSEHB and Rus-Baptist/Stunda;
- `Баптистъ` issue-level extension beyond official RSEHB fragments;
- Toronto samizdat issue and holding rows;
- EAAA confirmation for `Баптист Украины` and full `Братский вестник` disc coverage;
- a methodological distinction between `catalog_seen`, `link_visible`, `download_ok`, `page_counted`, and `ocr_ready`.

## Recommended repo patch, not done here

Create exactly these files in repo later:

1. `baptisty-rossii/research/79-periodical-corpus-master-ledger-2026-06-25.md`
2. `baptisty-rossii/research/raw-sources/periodicals/periodical-issue-census-seed.csv`
3. `baptisty-rossii/research/raw-sources/periodicals/samizdat-crosswalk-seed.csv`
4. Update `baptisty-rossii/research/00-master-source-index-glossary-map.md` with a short pointer, not full pasted material.

## Where the material feeds the series

| Repo section | ZIP periodical track to feed |
|---|---|
| `podpolnaya-pechat` | `Вестник спасения`, `Вестник истины`, `Братский листок`, `Бюллетень родственников узников` |
| `iniciativnaya-gruppa` | 1959–1965 split, Council of Churches documents, prisoner-relatives evidence |
| `vsehib-1944` | `Братский вестник` official line by period |
| `sovetskaya-noch` | official vs underground language under pressure |
| `yuzhnaya-shtunda` | `Баптист Украины`, `Гость`, `Христианин`, `Баптистъ` |
| `spravochnik` | title ranges, archive abbreviations, source-confidence rules |

## Discipline

Do not paste all v85 files into repo. Promote only stable ledgers and seed CSVs. Keep speculative crawl notes in ZIP until they are source-verified and normalized.


---

## [7] SOURCE: `baptists_v93/120-repo-clean-integration-plan-v86.md`

# v86 — чистый план интеграции ZIP в repo

## Цель

Не раздувать `baptisty-rossii/research` сотней новых файлов. В repo уже много research-pack файлов. ZIP v86 должен войти как компактный, управляемый периодический слой.

## Рекомендуемый вариант

Добавить в repo один новый файл:

`baptisty-rossii/research/79-periodical-corpus-ledger-2026-06-25.md`

И рядом, если нужны данные:

`baptisty-rossii/research/raw-sources/periodical-corpus-ledger-v86.csv`

## Что включить в 79-й файл

1. Карта источников:
   - РС ЕХБ official-visible;
   - Rus-Baptist/Stunda mirror;
   - EAAA institutional disks;
   - Toronto/Baylor samizdat;
   - Propovednik/MIR direct PDFs;
   - academic synthesis.

2. Corpus priority:
   - P0: `Баптистъ`, `Вестник спасения`, `Вестник истины`, `Бюллетень родственников узников`, `Братский листок СЦ`, `Братский вестник`.
   - P1: `Христианин`, `Утренняя звезда`, `Баптист Украины`.
   - P2: `Наша Семья`, `Слово Истины`, post-Soviet independent Baptist press.

3. Status fields:
   - `catalog_seen`
   - `link_visible`
   - `download_ok`
   - `page_counted`
   - `ocr_raw`
   - `ocr_checked`
   - `quote_ready`
   - `repo_integrated`

4. Immediate next tasks:
   - probe/download `Баптистъ` high-priority issues;
   - collect `Бюллетень` issue list and page counts;
   - verify `Братский листок` 247 items claim from full PDF/sbornik;
   - map `Братский вестник` 1945–1993 via EAAA + RSEHB + mirrors.

## What not to do

- Не копировать все MD из ZIP в repo.
- Не создавать 20 новых файлов по одной теме.
- Не помечать link-level находки как OCR-ready.
- Не смешивать официальный `Братский вестник` ВСЕХБ и подпольный `Братский листок` СЦ.


---

## [8] SOURCE: `baptists_v93/125-repo-v87-integration-warning.md`

# v87 — Repo integration warning: не заливать ZIP как свалку

Дата прохода: 2026-06-25.

## Контекст

Публичный репозиторий уже содержит `/baptisty-rossii/` и исследовательские файлы. По результатам предыдущей сверки, серия уже имеет структуру и source-packs. Поэтому следующий перенос из ZIP должен быть чистым и минимальным.

GitHub root: https://github.com/FedorMilovanov/gb-is-my-strength
Baptisty-Rossii path: https://github.com/FedorMilovanov/gb-is-my-strength/tree/main/baptisty-rossii

## Что переносить в repo первым

Один новый файл:

`baptisty-rossii/research/79-periodical-corpus-ledger-2026-06-25.md`

И один CSV:

`baptisty-rossii/research/raw-sources/periodical-authority-register-2026-06-25.csv`

## Что НЕ переносить сразу

- все файлы ZIP `01–125`;
- промежуточные crawl prompts;
- повторяющиеся README/CHANGELOG старых версий;
- CSV с непроверенными дублями без нормализации;
- claim-level строки без статуса источника.

## Как писать итоговый repo-ledger

Структура:

1. Карта периодики по эпохам.
2. Разделение: баптисты / евангельские христиане ВСЕХ / ВСЕХБ / СЦ ЕХБ / эмиграция / Украина / Дальний Восток.
3. Таблица доверия источников.
4. P0-issue census queue.
5. Что уже можно цитировать.
6. Что нельзя цитировать без page-level проверки.
7. Crawl-план на 5 batches.

## Приоритет для следующего агента

1. Нормализовать authority register.
2. Не трогать внешний вид сайта.
3. Не менять маршруты Astro.
4. Не разносить в десятки новых файлов.
5. Сделать один аккуратный PR с research-only добавлением.
