#!/usr/bin/env python3
"""Download the manually approved 63-item ephemera allowlist from Commons.

The allowlist was selected from contact sheets generated by the review-first
workflow. Current structured license metadata is re-fetched before every
original download. Files are preserved unchanged and verified with Pillow;
manifest, attribution ledger and SHA-256 sums are produced. Any missing item,
closed license or invalid image fails the final gate.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import html
import json
import re
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import requests
from PIL import Image

API = "https://commons.wikimedia.org/w/api.php"
USER_AGENT = (
    "TheLegendaryPoet-ApprovedEphemera/1.0 "
    "(+https://github.com/FedorMilovanov/Research; contact: viktorcoy2012@gmail.com)"
)
OPEN_LICENSE_PATTERNS = (
    "public domain", "pd-", "cc0", "cc by ", "cc-by-", "cc by-sa", "cc-by-sa",
    "creative commons attribution",
)
EXCLUDED_LICENSE_PATTERNS = (
    "fair use", "copyrighted", "noncommercial", "no derivatives", "all rights reserved",
)
EXT_FIELDS = "|".join([
    "LicenseShortName", "UsageTerms", "AttributionRequired", "Artist", "Credit",
    "Source", "DateTimeOriginal", "DateTime", "ImageDescription", "Categories",
])

SELECTED: tuple[tuple[str, str], ...] = (
    ('manuscript-lermontov', 'File:Смерть поэта. Рукопись непозволительного стиха, написанного Лермонтовым и распространенного Раевским. (1837) — 1.jpg'),
    ('manuscript-lermontov', 'File:Смерть поэта. Рукопись непозволительного стиха, написанного Лермонтовым и распространенного Раевским. (1837) — 2.jpg'),
    ('manuscript-lermontov', 'File:Княгиня Лиговская. Автограф Лермонтова.jpg'),
    ('manuscript-yesenin', 'File:Дарственная надпись Сергея Есенина Августе Миклашевской.jpg'),
    ('manuscript-yesenin', 'File:Автограф последнего стихотворения Есенина.jpg'),
    ('manuscript-yesenin', 'File:Автограф Сергея Есенина.png'),
    ('manuscript-mayakovsky', 'File:Маяковский Владимир автограф в Чукоккале 1910е.JPG'),
    ('manuscript-mayakovsky', 'File:Предсмертная записка Маяковского.jpg'),
    ('manuscript-mayakovsky', 'File:AvtografMayakovsky.jpg'),
    ('manuscript-mayakovsky', 'File:Mayakovsky A vy mogli by Autograph.jpg'),
    ('manuscript-blok', 'File:Блок Александр автограф 1910е.JPG'),
    ('manuscript-akhmatova', 'File:Ахматова Анна автограф.JPG'),
    ('manuscript-tsvetaeva', 'File:Рукопись.png'),
    ('manuscript-pasternak', 'File:Пастернак Борис автограф.JPG'),
    ('cover-russian-futurism', 'File:A Slap in the Face of Public Taste.jpg'),
    ('cover-russian-futurism', 'File:Zangezi.jpg'),
    ('cover-kruchenykh', "File:Cover of Little Duck's Nest… of Bad Words… (Kruchenykh-Rozanova, 1913).jpg"),
    ('cover-kruchenykh', 'File:Cover from Troe (Kazimir Malevich, 1913).jpg'),
    ('cover-kruchenykh', 'File:Victory over the Sun cover.jpg'),
    ('cover-kruchenykh', 'File:Huligany-v-derevne.jpg'),
    ('cover-mayakovsky', 'File:Mayakovsky books kruchyonyx stixi.png'),
    ('cover-mayakovsky', 'File:Majak ja.jpg'),
    ('cover-mayakovsky', 'File:Сборник стихов Владимира Маяковского "Я".jpg'),
    ('cover-mayakovsky', 'File:Dlja golosa. 1923-100.jpg'),
    ('cover-silver-age-journals', 'File:Весы журнал.jpg'),
    ('place-yesenin', 'File:Sergei Yesenin house museum, Tashkent.JPG'),
    ('place-yesenin', 'File:RybnoeDistrict 06-13 Konstantinovo village 06.jpg'),
    ('place-yesenin', 'File:RybnoeDistrict 06-13 Konstantinovo village 07.jpg'),
    ('place-mayakovsky', 'File:Moscow, Mayakovskogo Lane.jpg'),
    ('place-pasternak', 'File:Domo-muzeo de Boris Pasternak en Peredelkino 05.jpg'),
    ('place-pasternak', 'File:Domo-muzeo de Boris Pasternak en Peredelkino 04.jpg'),
    ('place-pasternak', 'File:Domo-muzeo de Boris Pasternak en Peredelkino 03.jpg'),
    ('place-pushkin', 'File:Prechistenka pushkin museum corner.jpg'),
    ('place-pushkin', 'File:Prechistenka pushkin museum side.jpg'),
    ('place-pushkin', 'File:683. Mikhailovskoye. (Pskov oblast).The main house of the museum-estate. Living rooms.JPG'),
    ('place-lermontov', 'File:Lermontov House Museum in Moscow.JPG'),
    ('place-akhmatova', 'File:Im Anna-Achmatowa-Wohnungsmuseum in St. Petersburg.jpg'),
    ('place-tsvetaeva', 'File:Interiors of the Memorial House-Museum of Marina Tsvetaeva in Elabuga-1.jpg'),
    ('place-tsvetaeva', 'File:Memorial House-Museum of Marina Tsvetaeva in Elabuga-2.jpg'),
    ('place-tsvetaeva', 'File:Memorial House-Museum of Marina Tsvetaeva in Elabuga.jpg'),
    ('manuscript-codex-sinaiticus', "File:Codex sinaticus (The S.S. Teacher's Edition-The Holy Bible - Plate XXII).jpg"),
    ('manuscript-codex-sinaiticus', 'File:Codex Sinaiticus-small.jpg'),
    ('manuscript-codex-sinaiticus', 'File:Codex Sinaiticus John 21,7.JPG'),
    ('manuscript-codex-sinaiticus', 'File:Codex Sinaiticus Matthew 1,1-2,5.JPG'),
    ('manuscript-dead-sea-scrolls', 'File:DeadSeaScrolls Amman Museum.jpg'),
    ('manuscript-dead-sea-scrolls', "File:Dead Sea Scroll -- the World's Oldest Secrets.jpg"),
    ('manuscript-dead-sea-scrolls', 'File:Detail From A Dead Sea Scroll.jpg'),
    ('manuscript-dead-sea-scrolls', 'File:Tetragrammaton11Q5-1.jpg'),
    ('manuscript-bodmer-p72', 'File:Papyrus Bodmer VIII.jpg'),
    ('manuscript-bodmer-p72', 'File:P072-1Pe-2.7-12-2.12-17-III-IV.jpg'),
    ('manuscript-hebrew-bible', 'File:Hebrew Bible Spain.jpg'),
    ('manuscript-hebrew-bible', "File:Hebrew Pentateuch (The S.S. Teacher's Edition-The Holy Bible - Plate VIII).jpg"),
    ('manuscript-hebrew-bible', 'File:Facing pages from Hebrew Bible, Spanish, late 13th century.jpg'),
    ('manuscript-hebrew-bible', 'File:Hebrew Psalter MS. Bodl. Or. 621, fol. 2b.jpg'),
    ('manuscript-hebrew-bible', 'File:Hebrew Psalter MS. Bodl. Or. 621, fol. 3a.jpg'),
    ('reformation-calvin', 'File:Portrait john calvin.jpg'),
    ('reformation-calvin', 'File:John Calvin Titian B.jpg'),
    ('reformation-calvin', 'File:Portrait of John Calvin, French School.jpg'),
    ('reformation-luther', 'File:Lucas Cranach (I) workshop - Martin Luther (Uffizi).jpg'),
    ('reformation-luther', 'File:Martin Luther, 1529.jpg'),
    ('puritan-john-owen', 'File:JohnOwenFrontispiece.jpg'),
    ('puritan-thomas-goodwin', 'File:ThomasGoodwin.jpg'),
    ('westminster-assembly', 'File:Englands Miraculous Preservation.png'),
)


@dataclass
class Record:
    number: int
    topic: str
    file_title: str
    local_file_name: str | None
    description_url: str
    original_url: str
    mime: str
    width: int | None
    height: int | None
    advertised_bytes: int | None
    downloaded_bytes: int | None
    sha256: str | None
    license_short_name: str
    usage_terms: str
    attribution_required: str
    artist: str
    credit: str
    source: str
    date: str
    status: str
    notes: str
    checked_at_utc: str


def clean_html(value: str | None) -> str:
    if not value:
        return ""
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", html.unescape(value))).strip()


def meta(ext: dict[str, Any], key: str) -> str:
    raw = ext.get(key, {})
    return clean_html(str(raw.get("value", ""))) if isinstance(raw, dict) else clean_html(str(raw))


def license_allowed(short: str, terms: str) -> bool:
    text = f"{short} {terms}".lower()
    return not any(x in text for x in EXCLUDED_LICENSE_PATTERNS) and any(x in text for x in OPEN_LICENSE_PATTERNS)


def request(session: requests.Session, url: str, *, params: dict[str, Any] | None = None, stream: bool = False) -> requests.Response:
    last: Exception | None = None
    for attempt in range(1, 5):
        try:
            response = session.get(url, params=params, stream=stream, allow_redirects=True, timeout=(30, 360))
            if response.status_code in {429, 500, 502, 503, 504} and attempt < 4:
                response.close(); time.sleep(attempt * 4); continue
            return response
        except requests.RequestException as exc:
            last = exc
            if attempt < 4:
                time.sleep(attempt * 4); continue
    raise RuntimeError(f"request failed: {last}")


def hydrate(session: requests.Session, titles: list[str]) -> dict[str, dict[str, Any]]:
    output: dict[str, dict[str, Any]] = {}
    for start in range(0, len(titles), 10):
        params = {
            "action": "query", "format": "json", "formatversion": 2,
            "titles": "|".join(titles[start:start+10]), "prop": "imageinfo",
            "iiprop": "url|size|mime|extmetadata", "iiextmetadatafilter": EXT_FIELDS,
            "iiextmetadatalanguage": "en", "iimetadataversion": "latest",
        }
        response = request(session, API, params=params); response.raise_for_status()
        for page in response.json().get("query", {}).get("pages", []):
            title = str(page.get("title", "")); infos = page.get("imageinfo") or []
            if infos: output[title] = infos[0]
    return output


def safe_name(number: int, topic: str, title: str, mime: str) -> str:
    stem = title.removeprefix("File:")
    stem = re.sub(r"\.[A-Za-z0-9]{2,5}$", "", stem)
    stem = re.sub(r'[\\/:*?"<>|]+', "_", stem)
    stem = re.sub(r"\s+", " ", stem).strip(" ._")[:105]
    ext = ".png" if mime == "image/png" else ".jpg"
    return f"{number:03d}__{topic}__{stem}{ext}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="approved-ephemera-originals")
    parser.add_argument("--max-file-mb", type=int, default=100)
    parser.add_argument("--pause", type=float, default=0.35)
    args = parser.parse_args()
    root = Path(args.output); root.mkdir(parents=True, exist_ok=True)
    max_bytes = args.max_file_mb * 1024 * 1024
    session = requests.Session(); session.headers.update({"User-Agent": USER_AGENT, "Accept": "application/json,text/html,*/*"})
    current = hydrate(session, [title for _, title in SELECTED])
    records: list[Record] = []; seen_sha: set[str] = set()

    for number, (topic, title) in enumerate(SELECTED, start=1):
        checked = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        info = current.get(title)
        if not info:
            records.append(Record(number, topic, title, None, "", "", "", None, None, None, None, None, "", "", "", "", "", "", "", "MISSING", "Commons item not returned", checked)); continue
        ext = info.get("extmetadata") or {}; short = meta(ext, "LicenseShortName"); terms = meta(ext, "UsageTerms")
        original = str(info.get("url", "")); description = str(info.get("descriptionurl", "")); mime = str(info.get("mime", "")).lower()
        advertised = int(info["size"]) if info.get("size") is not None else None
        base = dict(number=number, topic=topic, file_title=title, local_file_name=None, description_url=description, original_url=original, mime=mime,
                    width=int(info["width"]) if info.get("width") is not None else None, height=int(info["height"]) if info.get("height") is not None else None,
                    advertised_bytes=advertised, downloaded_bytes=None, sha256=None, license_short_name=short, usage_terms=terms,
                    attribution_required=meta(ext, "AttributionRequired"), artist=meta(ext, "Artist"), credit=meta(ext, "Credit"), source=meta(ext, "Source"),
                    date=meta(ext, "DateTimeOriginal") or meta(ext, "DateTime"), status="", notes="", checked_at_utc=checked)
        if mime not in {"image/jpeg", "image/png", "image/tiff", "image/webp"}:
            records.append(Record(**{**base, "status": "REJECTED_FORMAT", "notes": mime})); continue
        if not license_allowed(short, terms):
            records.append(Record(**{**base, "status": "REJECTED_LICENSE", "notes": f"{short}/{terms}"})); continue
        if advertised and advertised > max_bytes:
            records.append(Record(**{**base, "status": "REJECTED_SIZE", "notes": f"> {max_bytes}"})); continue
        try:
            response = request(session, original, stream=True); response.raise_for_status()
            local = safe_name(number, topic, title, mime); path = root/local; digest = hashlib.sha256(); size = 0
            with path.open("wb") as handle:
                for chunk in response.iter_content(1024*1024):
                    if not chunk: continue
                    size += len(chunk)
                    if size > max_bytes: raise ValueError("stream exceeds file limit")
                    digest.update(chunk); handle.write(chunk)
            response.close()
            with Image.open(path) as image:
                image.verify()
            sha = digest.hexdigest()
            if sha in seen_sha:
                path.unlink(missing_ok=True); records.append(Record(**{**base, "status": "DUPLICATE_SHA256", "downloaded_bytes": size, "sha256": sha, "notes": "byte-identical duplicate"})); continue
            seen_sha.add(sha)
            records.append(Record(**{**base, "local_file_name": local, "downloaded_bytes": size, "sha256": sha, "status": "DOWNLOADED", "notes": "manual allowlist; original verified"}))
            print(f"[saved] {number}/{len(SELECTED)} {local}", flush=True)
        except Exception as exc:
            if 'path' in locals(): path.unlink(missing_ok=True)
            records.append(Record(**{**base, "status": "DOWNLOAD_FAILED", "notes": f"{type(exc).__name__}: {exc}"}))
        time.sleep(args.pause)

    downloaded = [r for r in records if r.status == "DOWNLOADED"]
    report = {
        "collection": "approved-ephemera-originals-63",
        "generated_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "selected": len(SELECTED), "downloaded": len(downloaded),
        "total_bytes": sum(r.downloaded_bytes or 0 for r in downloaded),
        "license_counts": {x: sum(r.license_short_name == x for r in downloaded) for x in sorted({r.license_short_name for r in downloaded})},
        "topic_counts": {x: sum(r.topic == x for r in downloaded) for x in sorted({r.topic for r in downloaded})},
        "status_counts": {x: sum(r.status == x for r in records) for x in sorted({r.status for r in records})},
        "records": [asdict(r) for r in records],
    }
    (root/"manifest.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    fields = list(Record.__dataclass_fields__)
    with (root/"manifest.csv").open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields); writer.writeheader(); [writer.writerow(asdict(r)) for r in records]
    with (root/"SHA256SUMS.txt").open("w", encoding="utf-8") as handle:
        for r in downloaded: handle.write(f"{r.sha256}  {r.local_file_name}\n")
    (root/"README.md").write_text(
        f"# Approved ephemera originals\n\nSelected: **{len(SELECTED)}**  \nDownloaded: **{len(downloaded)}**  \nTotal bytes: **{report['total_bytes']}**\n\nEvery item was manually selected from contact sheets and revalidated against current Commons license metadata.\n",
        encoding="utf-8",
    )
    print(json.dumps({k: report[k] for k in ("selected", "downloaded", "total_bytes", "license_counts", "status_counts")}, ensure_ascii=False))
    return 0 if len(downloaded) == len(SELECTED) else 2


if __name__ == "__main__":
    raise SystemExit(main())
